"""Job — Polars (ETL), NumPy, SciPy; Mojo w `job/src/mojo/` (`function.job.bridge`)."""

from __future__ import annotations

from .bridge import (
    MOJO_PACKAGE_DIR,
    MojoKernelBridge,
    build_mojopkg,
    max_engine_available,
)
from . import array, export, frame, ingest, interpolate, linalg, optimize, signal, stats, transform
from .export import write_csv, write_database, write_delta, write_parquet
from .frame import (
    collect_lazy,
    concat_vertical,
    empty_frame,
    from_rows,
    iter_batches,
    scan_csv_lazy,
    scan_ndjson_lazy,
    scan_parquet_lazy,
    sink_parquet_lazy,
)
from .ingest import (
    read_csv,
    read_json,
    read_ndjson,
    read_parquet,
    scan_csv,
    scan_ipc,
    scan_ndjson,
    scan_parquet,
)
from .interpolate import griddata_points, interp_1d_linear, rbf_interpolate
from .linalg import (
    dot,
    eig_decompose,
    eigvalsh_symmetric,
    matmul,
    matrix_rank,
    norm_vector,
    solve_linear,
    svd_decompose,
)
from .optimize import curve_fit_model, find_root_scalar, linprog_simple, minimize_scalar_bounded, minimize_vector
from .pipeline import lazy_aggregate_then_collect, numeric_feature_pipeline
from .signal import butter_lowpass, convolve_same, fft_rfft, filtfilt_zero_phase, find_peaks_1d, welch_psd
from .stats import (
    chi2_contingency,
    describe_sample,
    ks_2samp_test,
    mannwhitneyu_test,
    normal_pdf,
    pearsonr_corr,
    spearmanr_corr,
    ttest_ind_samples,
)
from .transform import (
    filter_by_expr,
    group_agg,
    join_inner,
    join_left,
    melt_unpivot,
    pivot_table,
    select_columns,
    sort_by,
    with_derived,
)

__all__ = [
    "MOJO_PACKAGE_DIR",
    "MojoKernelBridge",
    "array",
    "build_mojopkg",
    "butter_lowpass",
    "chi2_contingency",
    "collect_lazy",
    "concat_vertical",
    "convolve_same",
    "curve_fit_model",
    "describe_sample",
    "dot",
    "eig_decompose",
    "eigvalsh_symmetric",
    "empty_frame",
    "export",
    "fft_rfft",
    "filter_by_expr",
    "find_peaks_1d",
    "find_root_scalar",
    "filtfilt_zero_phase",
    "frame",
    "from_rows",
    "griddata_points",
    "group_agg",
    "ingest",
    "interp_1d_linear",
    "interpolate",
    "iter_batches",
    "join_inner",
    "join_left",
    "ks_2samp_test",
    "lazy_aggregate_then_collect",
    "linalg",
    "linprog_simple",
    "mannwhitneyu_test",
    "matmul",
    "matrix_rank",
    "max_engine_available",
    "melt_unpivot",
    "minimize_scalar_bounded",
    "minimize_vector",
    "normal_pdf",
    "norm_vector",
    "numeric_feature_pipeline",
    "optimize",
    "pearsonr_corr",
    "pivot_table",
    "rbf_interpolate",
    "read_csv",
    "read_json",
    "read_ndjson",
    "read_parquet",
    "scan_csv",
    "scan_csv_lazy",
    "scan_ipc",
    "scan_ndjson",
    "scan_ndjson_lazy",
    "scan_parquet",
    "scan_parquet_lazy",
    "select_columns",
    "signal",
    "sink_parquet_lazy",
    "solve_linear",
    "sort_by",
    "spearmanr_corr",
    "stats",
    "svd_decompose",
    "transform",
    "ttest_ind_samples",
    "welch_psd",
    "with_derived",
    "write_csv",
    "write_database",
    "write_delta",
    "write_parquet",
]
