syntax = "proto3";

package blockchain.governance.enums;

option go_package = "github.com/chainrice/proto/blockchain/governance/enums";

// ProposalType defines the different types of governance proposals
enum ProposalType {
  // PROPOSAL_TYPE_UNSPECIFIED indicates an unspecified proposal type
  PROPOSAL_TYPE_UNSPECIFIED = 0;
  
  // PROPOSAL_TYPE_TEXT represents a text proposal for discussion
  PROPOSAL_TYPE_TEXT = 1;
  
  // PROPOSAL_TYPE_PARAMETER_CHANGE represents a parameter change proposal
  PROPOSAL_TYPE_PARAMETER_CHANGE = 2;
  
  // PROPOSAL_TYPE_SOFTWARE_UPGRADE represents a software upgrade proposal
  PROPOSAL_TYPE_SOFTWARE_UPGRADE = 3;
  
  // PROPOSAL_TYPE_MODULE_UPGRADE represents a module upgrade proposal
  PROPOSAL_TYPE_MODULE_UPGRADE = 4;
  
  // PROPOSAL_TYPE_CANCEL_SOFTWARE_UPGRADE represents canceling a software upgrade
  PROPOSAL_TYPE_CANCEL_SOFTWARE_UPGRADE = 5;
  
  // PROPOSAL_TYPE_COMMUNITY_POOL_SPEND represents spending from community pool
  PROPOSAL_TYPE_COMMUNITY_POOL_SPEND = 6;
  
  // PROPOSAL_TYPE_CLIENT_UPDATE represents a client update proposal
  PROPOSAL_TYPE_CLIENT_UPDATE = 7;
  
  // PROPOSAL_TYPE_CONNECTION_UPDATE represents a connection update proposal
  PROPOSAL_TYPE_CONNECTION_UPDATE = 8;
  
  // PROPOSAL_TYPE_CHANNEL_UPDATE represents a channel update proposal
  PROPOSAL_TYPE_CHANNEL_UPDATE = 9;
  
  // PROPOSAL_TYPE_VALIDATOR_SET_UPDATE represents a validator set update
  PROPOSAL_TYPE_VALIDATOR_SET_UPDATE = 10;
  
  // PROPOSAL_TYPE_TOKEN_ADD represents adding a new token
  PROPOSAL_TYPE_TOKEN_ADD = 11;
  
  // PROPOSAL_TYPE_TOKEN_REMOVE represents removing a token
  PROPOSAL_TYPE_TOKEN_REMOVE = 12;
  
  // PROPOSAL_TYPE_BRIDGE_UPDATE represents a bridge update proposal
  PROPOSAL_TYPE_BRIDGE_UPDATE = 13;
  
  // PROPOSAL_TYPE_FEE_UPDATE represents a fee update proposal
  PROPOSAL_TYPE_FEE_UPDATE = 14;
  
  // PROPOSAL_TYPE_EMERGENCY_PAUSE represents an emergency pause proposal
  PROPOSAL_TYPE_EMERGENCY_PAUSE = 15;
  
  // PROPOSAL_TYPE_EMERGENCY_RESUME represents an emergency resume proposal
  PROPOSAL_TYPE_EMERGENCY_RESUME = 16;
  
  // PROPOSAL_TYPE_TREASURY_UPDATE represents a treasury update proposal
  PROPOSAL_TYPE_TREASURY_UPDATE = 17;
  
  // PROPOSAL_TYPE_ORACLE_UPDATE represents an oracle update proposal
  PROPOSAL_TYPE_ORACLE_UPDATE = 18;
  
  // PROPOSAL_TYPE_CONTRACT_UPDATE represents a smart contract update proposal
  PROPOSAL_TYPE_CONTRACT_UPDATE = 19;
  
  // PROPOSAL_TYPE_NETWORK_UPDATE represents a network configuration update
  PROPOSAL_TYPE_NETWORK_UPDATE = 20;
}
