# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "google" {
  project                 = var.rice_gcp_project_id
  region                  = var.rice_gcp_region
  user_project_override   = true
}