apiVersion: v2
name: redis
description: Redis 7.x OSS Cluster with Redis Operator
type: application
version: 1.0.0
appVersion: "7.2"

dependencies:
  - name: redis-operator
    version: "1.2.0"
    repository: "https://spotahome.github.io/redis-operator"

