# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "databases_probe" {
  input = {
    module         = "databases"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    region         = var.rice_region
    db_class       = var.rice_db_instance_class
  }
}