// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlcgen

import (
	kit "github.com/RICE-Rob-Inn-Com-Ent/rice/service/kit/src"
)

type SqlcSchemaAnchor struct {
	ID kit.UUID `json:"id"`
}
