// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: sqlc_anchor.sql

package sqlcgen

import (
	"context"
)

const SqlcAnchorPing = `-- name: SqlcAnchorPing :one
SELECT 1::int AS ok
`

func (q *Queries) SqlcAnchorPing(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, SqlcAnchorPing)
	var ok int32
	err := row.Scan(&ok)
	return ok, err
}
