version: "3.9"

services:
  chain-rice-frontend:
    build:
      context: ./projects/chain-rice
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./projects/chain-rice:/app
    command: ["npm", "run", "dev"]

  backend:
    build:
      context: ./libs/backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./libs/backend:/app

  fastapi-bridge:
    build:
      context: ./libs/connection/FastAPI
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./libs/connection/FastAPI:/app

  jvm-bridge:
    build:
      context: ./libs/connection/JVM
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./libs/connection/JVM:/app

  php-bridge:
    build:
      context: ./libs/connection/PHP
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    volumes:
      - ./libs/connection/PHP:/app

  beam-bridge:
    build:
      context: ./libs/connection/BEAM
    dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ./libs/connection/BEAM:/app

  bots-core:
    build:
      context: ./bots/core
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./bots/core:/app

  bots-models:
    build:
      context: ./bots/models
      dockerfile: Dockerfile
    volumes:
      - ./bots/models:/app
