# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Remote state: use S3/GCS/azurerm in production; templates in environments/dev/backend.tf.

terraform {
  backend "local" {
    path = ".terraform/state/rice-prod.tfstate"
  }
}