# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# EKS / GKE / AKS — extend with real resources; probe validates wiring from root.
resource "terraform_data" "clusters_probe" {
  input = {
    module          = "clusters"
    deployment_key  = format("%s:%s", var.rice_cloud_provider, var.rice_region)
    environment     = var.rice_environment
    cloud_provider  = var.rice_cloud_provider
    region          = var.rice_region
    vpc_cidr        = var.rice_vpc_cidr
    k8s_name        = var.rice_k8s_cluster_name
    azs             = var.rice_availability_zones
    enable_gpu      = var.rice_enable_gpu
    gpu_type        = var.rice_gpu_instance_type
  }
}