# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_region" { type = string }
variable "rice_vpc_cidr" { type = string }
variable "rice_k8s_cluster_name" { type = string }
variable "rice_availability_zones" { type = list(string) }
variable "rice_enable_gpu" { type = bool }
variable "rice_gpu_instance_type" { type = string }