package database

// TODO:
// [ ] implement sqlc generated query wrappers:
//     all queries from database/src/sqlc/ — generated by sqlc
//     never write raw SQL outside sqlc query files
// [ ] implement query instrumentation:
//     every query gets OTel span with:
//     db.system=postgresql, db.statement=query_hash (not full SQL)
//     db.operation=select|insert|update|delete
// [ ] implement query timeout:
//     default timeout from RICE_DB_QUERY_TIMEOUT_S env var
//     applied via context.WithTimeout on every query

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
)

// QueryExecutor is the façade for sqlc-generated methods and ad-hoc queries on the pool.
// Point sqlc at this repo; generated code receives *pgxpool.Pool or pgx.Tx.
type QueryExecutor struct {
	Pool *pgxpool.Pool
}

// Exec runs a command (INSERT/UPDATE/DELETE) without returning rows.
func (q *QueryExecutor) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	if q == nil || q.Pool == nil {
		return pgconn.CommandTag{}, fmt.Errorf("database: nil query executor")
	}
	return q.Pool.Exec(ctx, sql, args...)
}

// Query runs a query and returns rows (caller must Close the Rows).
func (q *QueryExecutor) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	if q == nil || q.Pool == nil {
		return nil, fmt.Errorf("database: nil query executor")
	}
	return q.Pool.Query(ctx, sql, args...)
}

// QueryRow runs a query expected to return at most one row.
func (q *QueryExecutor) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	return q.Pool.QueryRow(ctx, sql, args...)
}

// CopyFrom uses the PostgreSQL COPY protocol for bulk loads (YugabyteDB-compatible).
func (q *QueryExecutor) CopyFrom(ctx context.Context, tableName pgx.Identifier, columnNames []string, rowSrc pgx.CopyFromSource) (int64, error) {
	if q == nil || q.Pool == nil {
		return 0, fmt.Errorf("database: nil query executor")
	}
	return q.Pool.CopyFrom(ctx, tableName, columnNames, rowSrc)
}

// Batch collects statements for a single round-trip (pgx batch).
func (q *QueryExecutor) Batch(ctx context.Context, b *pgx.Batch) pgx.BatchResults {
	if q == nil || q.Pool == nil {
		return nil
	}
	return q.Pool.SendBatch(ctx, b)
}
