// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"log/slog"
	"os"

	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.26.0"
	"go.opentelemetry.io/otel/trace"

	bench "github.com/RICE-Rob-Inn-Com-Ent/rice/service/bench/src"
	"dagger/rice/src/internal/dagger"
	"dagger/rice/src/internal/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject = querybuilder.GraphQLMarshaller

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r Rice) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *Rice) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func unwrapError(rerr error) string {
	var gqlErr *gqlerror.Error
	if errors.As(rerr, &gqlErr) {
		return gqlErr.Message
	}
	return rerr.Error()
}

func dispatch(ctx context.Context) (rerr error) {
	ctx = bench.InitDaggerModuleOTel(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer func() { _ = bench.ShutdownDaggerModuleOTel(context.WithoutCancel(ctx)) }()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, dag.Error(unwrapError(rerr))); err != nil {
				fmt.Println("failed to return error:", err)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		var exec *dagger.ExecError
		if errors.As(err, &exec) {
			return exec.Unwrap()
		}
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "Rice":
		switch fnName {
		case "Think":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Rice).Think(&parent, ctx)
		case "Audit":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Rice).Audit(&parent, ctx)
		case "Prepare":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			return nil, (*Rice).Prepare(&parent, ctx, project)
		case "Perform":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Rice).Perform(&parent, ctx)
		case "Cook":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			return nil, (*Rice).Cook(&parent, ctx, project)
		case "Forge":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Rice).Forge(&parent, ctx)
		case "Serve":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			return nil, (*Rice).Serve(&parent, ctx, project)
		case "Pour":
			var parent Rice
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return nil, (*Rice).Pour(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "":
		return dag.Module().
			WithObject(
				dag.TypeDef().WithObject("Rice", dagger.TypeDefWithObjectOpts{Description: "Rice is the module root type; methods become `dagger call <method>`.", SourceMap: dag.SourceMap("pour.go", 13, 6)}).
					WithFunction(
						dag.Function("Think",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Think checks that forge is up and prints compute / routing placeholders (SAGE TODOs).").
							WithSourceMap(dag.SourceMap("think.go", 9, 1))).
					WithFunction(
						dag.Function("Audit",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Audit runs format, lint, test, verify in parallel, then optional gate steps.").
							WithSourceMap(dag.SourceMap("audit.go", 97, 1))).
					WithFunction(
						dag.Function("Prepare",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Prepare creates a minimal custom/{project} scaffold (CHIEF TODO: mint generator).").
							WithSourceMap(dag.SourceMap("prepare.go", 9, 1)).
							WithArg("project", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("prepare.go", 9, 45)})).
					WithFunction(
						dag.Function("Perform",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Perform writes BARD hardware placeholder and refreshes MASON .envrc; skips interactive IDE/cloud prompts.").
							WithSourceMap(dag.SourceMap("perform.go", 9, 1))).
					WithFunction(
						dag.Function("Cook",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Cook prints compiler TODOs for CHIEF (mint not yet implemented).").
							WithSourceMap(dag.SourceMap("cook.go", 9, 1)).
							WithArg("project", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("cook.go", 9, 42)})).
					WithFunction(
						dag.Function("Forge",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Forge runs buck2 build //... then docker compose up -d via experimental privileged nesting (host Docker).").
							WithSourceMap(dag.SourceMap("forge.go", 9, 1))).
					WithFunction(
						dag.Function("Serve",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Serve runs a full Audit then prints production deploy TODOs.").
							WithSourceMap(dag.SourceMap("serve.go", 9, 1)).
							WithArg("project", dag.TypeDef().WithKind(dagger.TypeDefKindStringKind), dagger.FunctionWithArgOpts{SourceMap: dag.SourceMap("serve.go", 9, 43)})).
					WithFunction(
						dag.Function("Pour",
							dag.TypeDef().WithKind(dagger.TypeDefKindVoidKind).WithOptional(true)).
							WithDescription("Pour installs toolchains (pixi), exports CUE, generates protos, syncs language deps,\nruns CLERK hpack layout, writes MASON .envrc from CUE, and BARD hardware placeholder.").
							WithSourceMap(dag.SourceMap("pour.go", 57, 1)))), nil
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
