# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Remote state: see dev/backend.tf in this repo for commented s3/gcs/azurerm templates.

terraform {
  backend "local" {
    path = ".terraform/state/rice-stag.tfstate"
  }
}