# syntax=docker/dockerfile:1.6
FROM python:3.12-slim
WORKDIR /app
RUN pip install --no-cache-dir poetry==1.8.3
COPY pyproject.toml /app/
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root
COPY app /app/app
CMD ["celery", "-A", "app.worker", "worker", "-l", "info"]