# Elasticsearch configuration
discovery.type: single-node
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300
# Disable xpack security for dev
xpack.security.enabled: false
xpack.monitoring.collection.enabled: true
cluster.name: rice-dev
node.name: elasticsearch
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs
