apiVersion: v2
name: k8s
description: K8s Helm chart dependencies with ArgoCD
version: 1.1.0

dependencies:
  - name: nginx
    version: "15.0.0"
    repository: "https://charts.bitnami.com/bitnami"
  - name: argo-cd
    version: "7.6.6"
    repository: "https://argoproj.github.io/argo-helm"
  - name: postgresql
    version: "1.0.0"
    repository: "file://./charts/postgresql"
    condition: databases.postgresql.enabled
  - name: mongodb
    version: "1.0.0"
    repository: "file://./charts/mongodb"
    condition: databases.mongodb.enabled
  - name: redis
    version: "1.0.0"
    repository: "file://./charts/redis"
    condition: databases.redis.enabled
  - name: cockroachdb
    version: "1.0.0"
    repository: "file://./charts/cockroachdb"
    condition: databases.cockroachdb.enabled
  - name: cassandra
    version: "1.0.0"
    repository: "file://./charts/cassandra"
    condition: databases.cassandra.enabled
  - name: monitoring
    version: "1.0.0"
    repository: "file://./charts/monitoring"
    condition: monitoring.enabled
  - name: cluster-autoscaler
    version: "1.0.0"
    repository: "file://./charts/cluster-autoscaler"
    condition: serverless.clusterAutoscaler.enabled
  - name: knative
    version: "1.0.0"
    repository: "file://./charts/knative"
    condition: serverless.knative.enabled
  - name: keda
    version: "1.0.0"
    repository: "file://./charts/keda"
    condition: serverless.keda.enabled
