<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{{ .data.elixir.title }} - Rice Framework</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            background: linear-gradient(135deg, #e73c7e 0%, #23a6d5 100%);
            color: #333;
            padding: 2rem;
            min-height: 100vh;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            background: white;
            border-radius: 12px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3);
            overflow: hidden;
        }
        header {
            background: linear-gradient(135deg, #e73c7e 0%, #23a6d5 100%);
            color: white;
            padding: 2rem;
            text-align: center;
        }
        h1 { font-size: 2.5rem; margin-bottom: 0.5rem; }
        .subtitle { opacity: 0.9; font-size: 1.1rem; }
        .content { padding: 2rem; }
        .section {
            margin-bottom: 2rem;
            padding: 1.5rem;
            background: #f8f9fa;
            border-radius: 8px;
            border-left: 4px solid #e73c7e;
        }
        .section h2 {
            color: #e73c7e;
            margin-bottom: 1rem;
            font-size: 1.5rem;
        }
        .grid {
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
            gap: 1rem;
            margin-top: 1rem;
        }
        .card {
            background: white;
            padding: 1.5rem;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            border-top: 3px solid #e73c7e;
        }
        .card h3 {
            color: #333;
            margin-bottom: 0.5rem;
            font-size: 1.2rem;
        }
        .status {
            display: inline-block;
            padding: 0.25rem 0.75rem;
            border-radius: 20px;
            font-size: 0.85rem;
            font-weight: 600;
            margin-top: 0.5rem;
        }
        .status.running { background: #d4edda; color: #155724; }
        .status.connected { background: #d1ecf1; color: #0c5460; }
        .pid {
            color: #666;
            font-size: 0.9rem;
            font-family: monospace;
            margin-top: 0.5rem;
        }
        .db-info {
            background: white;
            padding: 1.5rem;
            border-radius: 8px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
            margin-top: 1rem;
        }
        .footer {
            text-align: center;
            padding: 1.5rem;
            background: #f8f9fa;
            color: #666;
            font-size: 0.9rem;
        }
    </style>
</head>
<body>
    <div class="container">
        <header>
            <h1>💧 {{ .data.elixir.title }}</h1>
            <p class="subtitle">BEAM Supervisor & CockroachDB Status</p>
        </header>
        <div class="content">
            <div class="section">
                <h2>⚡ BEAM Processes</h2>
                <div class="grid">
                    {{ range .data.elixir.processes }}
                    <div class="card">
                        <h3>{{ .name }}</h3>
                        <span class="status {{ .status }}">{{ .status }}</span>
                        <p class="pid">PID: {{ .pid }}</p>
                    </div>
                    {{ end }}
                </div>
            </div>
            <div class="section">
                <h2>🐛 CockroachDB</h2>
                <div class="db-info">
                    <h3>CockroachDB Status</h3>
                    <p><strong>Status:</strong> <span class="status {{ .data.elixir.cockroachdb.status }}">{{ .data.elixir.cockroachdb.status }}</span></p>
                    <p><strong>Version:</strong> {{ .data.elixir.cockroachdb.version }}</p>
                </div>
            </div>
        </div>
        <div class="footer">
            <p>Generated by Rice Framework • Last updated: {{ now | date "2006-01-02 15:04:05" }}</p>
        </div>
    </div>
</body>
</html>
