# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "routes_probe" {
  input = {
    module         = "routes"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    domain         = var.rice_domain
  }
}