# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_azure_subscription_effective" {
  value       = var.rice_azure_subscription_id
  sensitive   = true
  description = "Subscription ID passed into azurerm (may be empty when using CLI / OIDC)."
}