# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "azurerm" {
  features {}

  subscription_id = var.rice_azure_subscription_id != "" ? var.rice_azure_subscription_id : null
  tenant_id         = var.rice_azure_tenant_id != "" ? var.rice_azure_tenant_id : null
}