syntax = "proto3";

package gaming.nft_assets.enums;

option go_package = "github.com/rice-dev/gaming/nft-assets/enums";

// Типи NFT
enum NftType {
  NFT_TYPE_UNSPECIFIED = 0;
  
  // Колекційні NFT
  NFT_TYPE_COLLECTIBLE = 1;
  
  // Ігрові NFT
  NFT_TYPE_GAMING = 2;
  
  // Мистецькі NFT
  NFT_TYPE_ART = 3;
  
  // Музичні NFT
  NFT_TYPE_MUSIC = 4;
  
  // Відео NFT
  NFT_TYPE_VIDEO = 5;
  
  // Анімаційні NFT
  NFT_TYPE_ANIMATION = 6;
  
  // 3D моделі NFT
  NFT_TYPE_3D_MODEL = 7;
  
  // Аватари NFT
  NFT_TYPE_AVATAR = 8;
  
  // Персонажі NFT
  NFT_TYPE_CHARACTER = 9;
  
  // Зброя NFT
  NFT_TYPE_WEAPON = 10;
  
  // Броня NFT
  NFT_TYPE_ARMOR = 11;
  
  // Аксесуари NFT
  NFT_TYPE_ACCESSORY = 12;
  
  // Транспорт NFT
  NFT_TYPE_VEHICLE = 13;
  
  // Земля NFT
  NFT_TYPE_LAND = 14;
  
  // Будівлі NFT
  NFT_TYPE_BUILDING = 15;
  
  // Меблі NFT
  NFT_TYPE_FURNITURE = 16;
  
  // Декорації NFT
  NFT_TYPE_DECORATION = 17;
  
  // Природа NFT
  NFT_TYPE_NATURE = 18;
  
  // Рослини NFT
  NFT_TYPE_PLANT = 19;
  
  // Тварини NFT
  NFT_TYPE_ANIMAL = 20;
  
  // Предмети NFT
  NFT_TYPE_ITEM = 21;
  
  // Ресурси NFT
  NFT_TYPE_RESOURCE = 22;
  
  // Валюта NFT
  NFT_TYPE_CURRENCY = 23;
  
  // Токени NFT
  NFT_TYPE_TOKEN = 24;
  
  // Сертифікати NFT
  NFT_TYPE_CERTIFICATE = 25;
  
  // Дипломи NFT
  NFT_TYPE_DIPLOMA = 26;
  
  // Нагороди NFT
  NFT_TYPE_AWARD = 27;
  
  // Медалі NFT
  NFT_TYPE_MEDAL = 28;
  
  // Кубки NFT
  NFT_TYPE_TROPHY = 29;
  
  // Досягнення NFT
  NFT_TYPE_ACHIEVEMENT = 30;
  
  // Бейджі NFT
  NFT_TYPE_BADGE = 31;
  
  // Емблеми NFT
  NFT_TYPE_EMBLEM = 32;
  
  // Логотипи NFT
  NFT_TYPE_LOGO = 33;
  
  // Символи NFT
  NFT_TYPE_SYMBOL = 34;
  
  // Іконки NFT
  NFT_TYPE_ICON = 35;
  
  // Зображення NFT
  NFT_TYPE_IMAGE = 36;
  
  // Фотографії NFT
  NFT_TYPE_PHOTO = 37;
  
  // Малюнки NFT
  NFT_TYPE_DRAWING = 38;
  
  // Картини NFT
  NFT_TYPE_PAINTING = 39;
  
  // Скульптури NFT
  NFT_TYPE_SCULPTURE = 40;
  
  // Інсталяції NFT
  NFT_TYPE_INSTALLATION = 41;
  
  // Перформанси NFT
  NFT_TYPE_PERFORMANCE = 42;
  
  // Виставки NFT
  NFT_TYPE_EXHIBITION = 43;
  
  // Музеї NFT
  NFT_TYPE_MUSEUM = 44;
  
  // Галереї NFT
  NFT_TYPE_GALLERY = 45;
  
  // Колекції NFT
  NFT_TYPE_COLLECTION = 46;
  
  // Серії NFT
  NFT_TYPE_SERIES = 47;
  
  // Набори NFT
  NFT_TYPE_SET = 48;
  
  // Групи NFT
  NFT_TYPE_GROUP = 49;
  
  // Категорії NFT
  NFT_TYPE_CATEGORY = 50;
  
  // Класи NFT
  NFT_TYPE_CLASS = 51;
  
  // Типи NFT
  NFT_TYPE_TYPE = 52;
  
  // Види NFT
  NFT_TYPE_KIND = 53;
  
  // Сорти NFT
  NFT_TYPE_SORT = 54;
  
  // Різновиди NFT
  NFT_TYPE_VARIETY = 55;
  
  // Форми NFT
  NFT_TYPE_FORM = 56;
  
  // Форми NFT
  NFT_TYPE_SHAPE = 57;
  
  // Форми NFT
  NFT_TYPE_FIGURE = 58;
  
  // Паттерни NFT
  NFT_TYPE_PATTERN = 59;
  
  // Стилі NFT
  NFT_TYPE_STYLE = 60;
  
  // Мода NFT
  NFT_TYPE_FASHION = 61;
  
  // Тренди NFT
  NFT_TYPE_TREND = 62;
  
  // Режими NFT
  NFT_TYPE_MODE = 63;
  
  // Манери NFT
  NFT_TYPE_MANNER = 64;
  
  // Способи NFT
  NFT_TYPE_WAY = 65;
  
  // Методи NFT
  NFT_TYPE_METHOD = 66;
  
  // Техніки NFT
  NFT_TYPE_TECHNIQUE = 67;
  
  // Підходи NFT
  NFT_TYPE_APPROACH = 68;
  
  // Стратегії NFT
  NFT_TYPE_STRATEGY = 69;
  
  // Тактики NFT
  NFT_TYPE_TACTIC = 70;
  
  // Плани NFT
  NFT_TYPE_PLAN = 71;
  
  // Схеми NFT
  NFT_TYPE_SCHEME = 72;
  
  // Системи NFT
  NFT_TYPE_SYSTEM = 73;
  
  // Процеси NFT
  NFT_TYPE_PROCESS = 74;
  
  // Процедури NFT
  NFT_TYPE_PROCEDURE = 75;
  
  // Протоколи NFT
  NFT_TYPE_PROTOCOL = 76;
  
  // Стандарти NFT
  NFT_TYPE_STANDARD = 77;
  
  // Правила NFT
  NFT_TYPE_RULE = 78;
  
  // Регуляції NFT
  NFT_TYPE_REGULATION = 79;
  
  // Закони NFT
  NFT_TYPE_LAW = 80;
  
  // Акти NFT
  NFT_TYPE_ACT = 81;
  
  // Статути NFT
  NFT_TYPE_STATUTE = 82;
  
  // Ординанси NFT
  NFT_TYPE_ORDINANCE = 83;
  
  // Декрети NFT
  NFT_TYPE_DECREE = 84;
  
  // Едикти NFT
  NFT_TYPE_EDICT = 85;
  
  // Мандати NFT
  NFT_TYPE_MANDATE = 86;
  
  // Накази NFT
  NFT_TYPE_ORDER = 87;
  
  // Команди NFT
  NFT_TYPE_COMMAND = 88;
  
  // Інструкції NFT
  NFT_TYPE_INSTRUCTION = 89;
  
  // Напрямки NFT
  NFT_TYPE_DIRECTION = 90;
  
  // Керівництво NFT
  NFT_TYPE_GUIDANCE = 91;
  
  // Поради NFT
  NFT_TYPE_ADVICE = 92;
  
  // Пропозиції NFT
  NFT_TYPE_SUGGESTION = 93;
  
  // Рекомендації NFT
  NFT_TYPE_RECOMMENDATION = 94;
  
  // Пропозиції NFT
  NFT_TYPE_PROPOSAL = 95;
  
  // Пропозиції NFT
  NFT_TYPE_OFFER = 96;
  
  // Ставки NFT
  NFT_TYPE_BID = 97;
  
  // Аукціони NFT
  NFT_TYPE_AUCTION = 98;
  
  // Продажі NFT
  NFT_TYPE_SALE = 99;
  
  // Покупки NFT
  NFT_TYPE_PURCHASE = 100;
}
