// Code generated by generate_module.sh from protos. DO NOT EDIT.
import Foundation

class AuthService {
    
    // Create auth
    func createAuth(request: AuthRequest) async throws -> AuthResponse {
        // TODO: Implement from proto definition
        return AuthResponse(
            id: request.id,
            name: request.name,
            description: request.description
        )
    }
    
    // Get auth
    func getAuth(id: String) async throws -> AuthResponse {
        // TODO: Implement from proto definition
        return AuthResponse(
            id: id,
            name: "Sample auth",
            description: "Sample description"
        )
    }
}

struct AuthRequest: Codable {
    let id: String
    let name: String
    let description: String
}

struct AuthResponse: Codable {
    let id: String
    let name: String
    let description: String
}
