"""Helper — public gateway for settings, logging, errors, retry, schemas, validation, conversions.

Importing only binds submodules; it does not configure logging or load secrets.
Call ``configure_logging()`` and ``get_settings()`` at application startup when needed.
"""

from __future__ import annotations

__version__ = "0.1.0"

from .const import (
    DATE_ISO8601_STRFTIME,
    DATETIME_FORMAT,
    DATETIME_ISO8601_UTC_STRFTIME,
    DEFAULT_TEXT_ENCODING,
    ENCODING,
    ERROR_CODE_PREFIX,
    HELPER_DEFAULT_DATA_DIR,
    HELPER_DEFAULT_LOG_DIR,
    HELPER_MODULE_ROOT,
    HELPER_SRC_DIR,
    IO_CHUNK_MAX_BYTES,
    IO_CONNECT_TIMEOUT_S,
    IO_LINE_BUFFER_BYTES,
    IO_POOL_TIMEOUT_S,
    IO_READ_TIMEOUT_S,
    IO_SOCKET_TIMEOUT_S,
    IO_STREAM_BUFFER_BYTES,
    IO_WRITE_TIMEOUT_S,
    LOGURU_BACKTRACE,
    LOGURU_COMPRESSION,
    LOGURU_DIAGNOSE,
    LOGURU_ENQUEUE,
    LOGURU_FORMAT_JSON_FIELDS,
    LOGURU_FORMAT_TEXT,
    LOGURU_RETENTION,
    LOGURU_ROTATION_SIZE,
    LOGURU_SINK_QUEUE_SIZE,
    MAX_RETRY_ATTEMPTS,
    PYDANTIC_SCHEMA_CONFIG,
    PYDANTIC_SETTINGS_CONFIG_DEFAULTS,
    RETRY_BACKOFF_MAX,
    RETRY_BACKOFF_MIN,
    RETRY_DEFAULT_BUDGET_S,
    RETRY_DEFAULT_MAX_ATTEMPTS,
    RETRY_DEFAULT_MULTIPLIER,
    RETRY_EXPONENTIAL_MAX_S,
    RETRY_EXPONENTIAL_MIN_S,
    RETRY_IDEMPOTENT_MAX_ATTEMPTS,
    RETRY_IDEMPOTENT_WAIT_S,
    RETRY_JITTER_MAX_ATTEMPTS,
    RETRY_JITTER_MAX_S,
    RETRY_JITTER_MIN_S,
    RETRY_JITTER_MULTIPLIER,
    RETRY_MESSAGE_MATCH_MAX_ATTEMPTS,
    RETRY_MESSAGE_MATCH_MAX_S,
    RETRY_MESSAGE_MATCH_MIN_S,
)
from .convert import coerce_json, model_to_dict, parse_json, parse_model
from .error import (
    CircuitOpenError,
    ContextLimitError,
    GuardError,
    MaxRetriesExceeded,
    ModelError,
    RiceError,
    StorageError,
    StreamError,
    StructuredError,
    ValidationError,
)
from .log import bind_context, configure_logging, logger
from .retry import log_retry_state, retry_transient_io, retry_with_jitter
from .schema import NonEmptyStr, Page, SchemaBase, TimestampedSchema
from .settings import HelperSettings, get_settings
from .validate import EmailMixin, validate_payload, validate_slug

Settings = HelperSettings

__all__ = [
    "DATETIME_FORMAT",
    "DATETIME_ISO8601_UTC_STRFTIME",
    "DATE_ISO8601_STRFTIME",
    "DEFAULT_TEXT_ENCODING",
    "ENCODING",
    "ERROR_CODE_PREFIX",
    "HELPER_DEFAULT_DATA_DIR",
    "HELPER_DEFAULT_LOG_DIR",
    "HELPER_MODULE_ROOT",
    "HELPER_SRC_DIR",
    "IO_CHUNK_MAX_BYTES",
    "IO_CONNECT_TIMEOUT_S",
    "IO_LINE_BUFFER_BYTES",
    "IO_POOL_TIMEOUT_S",
    "IO_READ_TIMEOUT_S",
    "IO_SOCKET_TIMEOUT_S",
    "IO_STREAM_BUFFER_BYTES",
    "IO_WRITE_TIMEOUT_S",
    "LOGURU_BACKTRACE",
    "LOGURU_COMPRESSION",
    "LOGURU_DIAGNOSE",
    "LOGURU_ENQUEUE",
    "LOGURU_FORMAT_JSON_FIELDS",
    "LOGURU_FORMAT_TEXT",
    "LOGURU_RETENTION",
    "LOGURU_ROTATION_SIZE",
    "LOGURU_SINK_QUEUE_SIZE",
    "MAX_RETRY_ATTEMPTS",
    "PYDANTIC_SCHEMA_CONFIG",
    "PYDANTIC_SETTINGS_CONFIG_DEFAULTS",
    "RETRY_BACKOFF_MAX",
    "RETRY_BACKOFF_MIN",
    "RETRY_DEFAULT_BUDGET_S",
    "RETRY_DEFAULT_MAX_ATTEMPTS",
    "RETRY_DEFAULT_MULTIPLIER",
    "RETRY_EXPONENTIAL_MAX_S",
    "RETRY_EXPONENTIAL_MIN_S",
    "RETRY_IDEMPOTENT_MAX_ATTEMPTS",
    "RETRY_IDEMPOTENT_WAIT_S",
    "RETRY_JITTER_MAX_ATTEMPTS",
    "RETRY_JITTER_MAX_S",
    "RETRY_JITTER_MIN_S",
    "RETRY_JITTER_MULTIPLIER",
    "RETRY_MESSAGE_MATCH_MAX_ATTEMPTS",
    "RETRY_MESSAGE_MATCH_MAX_S",
    "RETRY_MESSAGE_MATCH_MIN_S",
    "CircuitOpenError",
    "ContextLimitError",
    "EmailMixin",
    "GuardError",
    "HelperSettings",
    "MaxRetriesExceeded",
    "ModelError",
    "NonEmptyStr",
    "Page",
    "RiceError",
    "SchemaBase",
    "Settings",
    "StorageError",
    "StreamError",
    "StructuredError",
    "TimestampedSchema",
    "ValidationError",
    "__version__",
    "bind_context",
    "coerce_json",
    "configure_logging",
    "get_settings",
    "log_retry_state",
    "logger",
    "model_to_dict",
    "parse_json",
    "parse_model",
    "retry_transient_io",
    "retry_with_jitter",
    "validate_payload",
    "validate_slug",
]
