// Code generated by generate_module.sh from protos. DO NOT EDIT.
import 'dart:async';

class AuthService {
  Future<AuthResponse> createAuth(AuthRequest request) async {
    // TODO: Implement from proto definition
    return AuthResponse(
      id: request.id,
      name: request.name,
      description: request.description,
    );
  }
  
  Future<AuthResponse> getAuth(String id) async {
    // TODO: Implement from proto definition
    return AuthResponse(
      id: id,
      name: 'Sample auth',
      description: 'Sample description',
    );
  }
}

class AuthRequest {
  final String id;
  final String name;
  final String description;
  
  AuthRequest({
    required this.id,
    required this.name,
    required this.description,
  });
}

class AuthResponse {
  final String id;
  final String name;
  final String description;
  
  AuthResponse({
    required this.id,
    required this.name,
    required this.description,
  });
}
