syntax = "proto3";

package blockchain.consensus.enums;

option go_package = "github.com/chainrice/proto/blockchain/consensus/enums";

// ConsensusAlgorithm defines the different consensus algorithms
enum ConsensusAlgorithm {
  // CONSENSUS_ALGORITHM_UNSPECIFIED indicates an unspecified consensus algorithm
  CONSENSUS_ALGORITHM_UNSPECIFIED = 0;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_WORK represents Proof of Work consensus
  CONSENSUS_ALGORITHM_PROOF_OF_WORK = 1;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_STAKE represents Proof of Stake consensus
  CONSENSUS_ALGORITHM_PROOF_OF_STAKE = 2;
  
  // CONSENSUS_ALGORITHM_DELEGATED_PROOF_OF_STAKE represents Delegated Proof of Stake
  CONSENSUS_ALGORITHM_DELEGATED_PROOF_OF_STAKE = 3;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_AUTHORITY represents Proof of Authority consensus
  CONSENSUS_ALGORITHM_PROOF_OF_AUTHORITY = 4;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_HISTORY represents Proof of History consensus
  CONSENSUS_ALGORITHM_PROOF_OF_HISTORY = 5;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_SPACE represents Proof of Space consensus
  CONSENSUS_ALGORITHM_PROOF_OF_SPACE = 6;
  
  // CONSENSUS_ALGORITHM_PROOF_OF_TIME represents Proof of Time consensus
  CONSENSUS_ALGORITHM_PROOF_OF_TIME = 7;
  
  // CONSENSUS_ALGORITHM_BYZANTINE_FAULT_TOLERANCE represents Byzantine Fault Tolerance
  CONSENSUS_ALGORITHM_BYZANTINE_FAULT_TOLERANCE = 8;
  
  // CONSENSUS_ALGORITHM_PRACTICAL_BYZANTINE_FAULT_TOLERANCE represents Practical BFT
  CONSENSUS_ALGORITHM_PRACTICAL_BYZANTINE_FAULT_TOLERANCE = 9;
  
  // CONSENSUS_ALGORITHM_FEDERATED_BYZANTINE_AGREEMENT represents Federated BFT
  CONSENSUS_ALGORITHM_FEDERATED_BYZANTINE_AGREEMENT = 10;
  
  // CONSENSUS_ALGORITHM_TENDermint represents Tendermint consensus
  CONSENSUS_ALGORITHM_TENDERMINT = 11;
  
  // CONSENSUS_ALGORITHM_CASPER represents Casper consensus
  CONSENSUS_ALGORITHM_CASPER = 12;
  
  // CONSENSUS_ALGORITHM_HONEY_BADGER represents Honey Badger BFT
  CONSENSUS_ALGORITHM_HONEY_BADGER = 13;
  
  // CONSENSUS_ALGORITHM_RAFT represents Raft consensus
  CONSENSUS_ALGORITHM_RAFT = 14;
  
  // CONSENSUS_ALGORITHM_PBFT represents Practical Byzantine Fault Tolerance
  CONSENSUS_ALGORITHM_PBFT = 15;
}
