syntax = "proto3";

package energy.generation.enums;

// Types of fuels used in power generation
enum FuelType {
  // Coal (bituminous)
  FUEL_TYPE_BITUMINOUS_COAL = 0;
  
  // Coal (sub-bituminous)
  FUEL_TYPE_SUB_BITUMINOUS_COAL = 1;
  
  // Coal (lignite)
  FUEL_TYPE_LIGNITE = 2;
  
  // Coal (anthracite)
  FUEL_TYPE_ANTHRACITE = 3;
  
  // Coal (coking coal)
  FUEL_TYPE_COKING_COAL = 4;
  
  // Coal (thermal coal)
  FUEL_TYPE_THERMAL_COAL = 5;
  
  // Natural gas
  FUEL_TYPE_NATURAL_GAS = 6;
  
  // Liquefied natural gas (LNG)
  FUEL_TYPE_LNG = 7;
  
  // Compressed natural gas (CNG)
  FUEL_TYPE_CNG = 8;
  
  // Shale gas
  FUEL_TYPE_SHALE_GAS = 9;
  
  // Coalbed methane
  FUEL_TYPE_COALBED_METHANE = 10;
  
  // Associated gas
  FUEL_TYPE_ASSOCIATED_GAS = 11;
  
  // Non-associated gas
  FUEL_TYPE_NON_ASSOCIATED_GAS = 12;
  
  // Biogas
  FUEL_TYPE_BIOGAS = 13;
  
  // Landfill gas
  FUEL_TYPE_LANDFILL_GAS = 14;
  
  // Sewage gas
  FUEL_TYPE_SEWAGE_GAS = 15;
  
  // Digester gas
  FUEL_TYPE_DIGESTER_GAS = 16;
  
  // Syngas
  FUEL_TYPE_SYNGAS = 17;
  
  // Producer gas
  FUEL_TYPE_PRODUCER_GAS = 18;
  
  // Refinery gas
  FUEL_TYPE_REFINERY_GAS = 19;
  
  // Coke oven gas
  FUEL_TYPE_COKE_OVEN_GAS = 20;
  
  // Blast furnace gas
  FUEL_TYPE_BLAST_FURNACE_GAS = 21;
  
  // Propane
  FUEL_TYPE_PROPANE = 22;
  
  // Butane
  FUEL_TYPE_BUTANE = 23;
  
  // Ethane
  FUEL_TYPE_ETHANE = 24;
  
  // Pentane
  FUEL_TYPE_PENTANE = 25;
  
  // Hexane
  FUEL_TYPE_HEXANE = 26;
  
  // Heptane
  FUEL_TYPE_HEPTANE = 27;
  
  // Octane
  FUEL_TYPE_OCTANE = 28;
  
  // Diesel fuel
  FUEL_TYPE_DIESEL = 29;
  
  // Gasoline
  FUEL_TYPE_GASOLINE = 30;
  
  // Kerosene
  FUEL_TYPE_KEROSENE = 31;
  
  // Jet fuel
  FUEL_TYPE_JET_FUEL = 32;
  
  // Heavy fuel oil
  FUEL_TYPE_HEAVY_FUEL_OIL = 33;
  
  // Light fuel oil
  FUEL_TYPE_LIGHT_FUEL_OIL = 34;
  
  // Medium fuel oil
  FUEL_TYPE_MEDIUM_FUEL_OIL = 35;
  
  // Marine fuel oil
  FUEL_TYPE_MARINE_FUEL_OIL = 36;
  
  // Bunker fuel oil
  FUEL_TYPE_BUNKER_FUEL_OIL = 37;
  
  // Residual fuel oil
  FUEL_TYPE_RESIDUAL_FUEL_OIL = 38;
  
  // Distillate fuel oil
  FUEL_TYPE_DISTILLATE_FUEL_OIL = 39;
  
  // Crude oil
  FUEL_TYPE_CRUDE_OIL = 40;
  
  // Refined oil
  FUEL_TYPE_REFINED_OIL = 41;
  
  // Vegetable oil
  FUEL_TYPE_VEGETABLE_OIL = 42;
  
  // Palm oil
  FUEL_TYPE_PALM_OIL = 43;
  
  // Soybean oil
  FUEL_TYPE_SOYBEAN_OIL = 44;
  
  // Rapeseed oil
  FUEL_TYPE_RAPESEED_OIL = 45;
  
  // Sunflower oil
  FUEL_TYPE_SUNFLOWER_OIL = 46;
  
  // Corn oil
  FUEL_TYPE_CORN_OIL = 47;
  
  // Canola oil
  FUEL_TYPE_CANOLA_OIL = 48;
  
  // Jatropha oil
  FUEL_TYPE_JATROPHA_OIL = 49;
  
  // Algae oil
  FUEL_TYPE_ALGAE_OIL = 50;
  
  // Biodiesel
  FUEL_TYPE_BIODIESEL = 51;
  
  // Ethanol
  FUEL_TYPE_ETHANOL = 52;
  
  // Methanol
  FUEL_TYPE_METHANOL = 53;
  
  // Propanol
  FUEL_TYPE_PROPANOL = 54;
  
  // Butanol
  FUEL_TYPE_BUTANOL = 55;
  
  // Pentanol
  FUEL_TYPE_PENTANOL = 56;
  
  // Hexanol
  FUEL_TYPE_HEXANOL = 57;
  
  // Octanol
  FUEL_TYPE_OCTANOL = 58;
  
  // Wood
  FUEL_TYPE_WOOD = 59;
  
  // Wood chips
  FUEL_TYPE_WOOD_CHIPS = 60;
  
  // Wood pellets
  FUEL_TYPE_WOOD_PELLETS = 61;
  
  // Sawdust
  FUEL_TYPE_SAWDUST = 62;
  
  // Bark
  FUEL_TYPE_BARK = 63;
  
  // Forest residues
  FUEL_TYPE_FOREST_RESIDUES = 64;
  
  // Agricultural residues
  FUEL_TYPE_AGRICULTURAL_RESIDUES = 65;
  
  // Straw
  FUEL_TYPE_STRAW = 66;
  
  // Bagasse
  FUEL_TYPE_BAGASSE = 67;
  
  // Rice husks
  FUEL_TYPE_RICE_HUSKS = 68;
  
  // Corn stover
  FUEL_TYPE_CORN_STOVER = 69;
  
  // Wheat straw
  FUEL_TYPE_WHEAT_STRAW = 70;
  
  // Barley straw
  FUEL_TYPE_BARLEY_STRAW = 71;
  
  // Oat straw
  FUEL_TYPE_OAT_STRAW = 72;
  
  // Rye straw
  FUEL_TYPE_RYE_STRAW = 73;
  
  // Switchgrass
  FUEL_TYPE_SWITCHGRASS = 74;
  
  // Miscanthus
  FUEL_TYPE_MISCANTHUS = 75;
  
  // Willow
  FUEL_TYPE_WILLOW = 76;
  
  // Poplar
  FUEL_TYPE_POPLAR = 77;
  
  // Eucalyptus
  FUEL_TYPE_EUCALYPTUS = 78;
  
  // Bamboo
  FUEL_TYPE_BAMBOO = 79;
  
  // Energy crops
  FUEL_TYPE_ENERGY_CROPS = 80;
  
  // Municipal solid waste
  FUEL_TYPE_MSW = 81;
  
  // Industrial waste
  FUEL_TYPE_INDUSTRIAL_WASTE = 82;
  
  // Medical waste
  FUEL_TYPE_MEDICAL_WASTE = 83;
  
  // Hazardous waste
  FUEL_TYPE_HAZARDOUS_WASTE = 84;
  
  // Sewage sludge
  FUEL_TYPE_SEWAGE_SLUDGE = 85;
  
  // Animal waste
  FUEL_TYPE_ANIMAL_WASTE = 86;
  
  // Poultry litter
  FUEL_TYPE_POULTRY_LITTER = 87;
  
  // Cattle manure
  FUEL_TYPE_CATTLE_MANURE = 88;
  
  // Pig manure
  FUEL_TYPE_PIG_MANURE = 89;
  
  // Horse manure
  FUEL_TYPE_HORSE_MANURE = 90;
  
  // Sheep manure
  FUEL_TYPE_SHEEP_MANURE = 91;
  
  // Goat manure
  FUEL_TYPE_GOAT_MANURE = 92;
  
  // Chicken manure
  FUEL_TYPE_CHICKEN_MANURE = 93;
  
  // Duck manure
  FUEL_TYPE_DUCK_MANURE = 94;
  
  // Turkey manure
  FUEL_TYPE_TURKEY_MANURE = 95;
  
  // Fish waste
  FUEL_TYPE_FISH_WASTE = 96;
  
  // Algae
  FUEL_TYPE_ALGAE = 97;
  
  // Seaweed
  FUEL_TYPE_SEAWEED = 98;
  
  // Kelp
  FUEL_TYPE_KELP = 99;
  
  // Water hyacinth
  FUEL_TYPE_WATER_HYACINTH = 100;
  
  // Duckweed
  FUEL_TYPE_DUCKWEED = 101;
  
  // Lemna
  FUEL_TYPE_LEMNA = 102;
  
  // Spirulina
  FUEL_TYPE_SPIRULINA = 103;
  
  // Chlorella
  FUEL_TYPE_CHLORELLA = 104;
  
  // Scenedesmus
  FUEL_TYPE_SCENEDESMUS = 105;
  
  // Hydrogen
  FUEL_TYPE_HYDROGEN = 106;
  
  // Ammonia
  FUEL_TYPE_AMMONIA = 107;
  
  // Methane
  FUEL_TYPE_METHANE = 108;
  
  // Ethylene
  FUEL_TYPE_ETHYLENE = 109;
  
  // Acetylene
  FUEL_TYPE_ACETYLENE = 110;
  
  // Carbon monoxide
  FUEL_TYPE_CARBON_MONOXIDE = 111;
  
  // Carbon dioxide
  FUEL_TYPE_CARBON_DIOXIDE = 112;
  
  // Nitrous oxide
  FUEL_TYPE_NITROUS_OXIDE = 113;
  
  // Sulfur dioxide
  FUEL_TYPE_SULFUR_DIOXIDE = 114;
  
  // Nitrogen oxides
  FUEL_TYPE_NITROGEN_OXIDES = 115;
  
  // Volatile organic compounds
  FUEL_TYPE_VOC = 116;
  
  // Particulate matter
  FUEL_TYPE_PM = 117;
  
  // Uranium
  FUEL_TYPE_URANIUM = 118;
  
  // Plutonium
  FUEL_TYPE_PLUTONIUM = 119;
  
  // Thorium
  FUEL_TYPE_THORIUM = 120;
  
  // Deuterium
  FUEL_TYPE_DEUTERIUM = 121;
  
  // Tritium
  FUEL_TYPE_TRITIUM = 122;
  
  // Helium-3
  FUEL_TYPE_HELIUM_3 = 123;
  
  // Lithium
  FUEL_TYPE_LITHIUM = 124;
  
  // Beryllium
  FUEL_TYPE_BERYLLIUM = 125;
  
  // Boron
  FUEL_TYPE_BORON = 126;
  
  // Carbon
  FUEL_TYPE_CARBON = 127;
  
  // Nitrogen
  FUEL_TYPE_NITROGEN = 128;
  
  // Oxygen
  FUEL_TYPE_OXYGEN = 129;
  
  // Fluorine
  FUEL_TYPE_FLUORINE = 130;
  
  // Neon
  FUEL_TYPE_NEON = 131;
  
  // Sodium
  FUEL_TYPE_SODIUM = 132;
  
  // Magnesium
  FUEL_TYPE_MAGNESIUM = 133;
  
  // Aluminum
  FUEL_TYPE_ALUMINUM = 134;
  
  // Silicon
  FUEL_TYPE_SILICON = 135;
  
  // Phosphorus
  FUEL_TYPE_PHOSPHORUS = 136;
  
  // Sulfur
  FUEL_TYPE_SULFUR = 137;
  
  // Chlorine
  FUEL_TYPE_CHLORINE = 138;
  
  // Argon
  FUEL_TYPE_ARGON = 139;
  
  // Potassium
  FUEL_TYPE_POTASSIUM = 140;
  
  // Calcium
  FUEL_TYPE_CALCIUM = 141;
  
  // Titanium
  FUEL_TYPE_TITANIUM = 142;
  
  // Vanadium
  FUEL_TYPE_VANADIUM = 143;
  
  // Chromium
  FUEL_TYPE_CHROMIUM = 144;
  
  // Manganese
  FUEL_TYPE_MANGANESE = 145;
  
  // Iron
  FUEL_TYPE_IRON = 146;
  
  // Cobalt
  FUEL_TYPE_COBALT = 147;
  
  // Nickel
  FUEL_TYPE_NICKEL = 148;
  
  // Copper
  FUEL_TYPE_COPPER = 149;
  
  // Zinc
  FUEL_TYPE_ZINC = 150;
  
  // Gallium
  FUEL_TYPE_GALLIUM = 151;
  
  // Germanium
  FUEL_TYPE_GERMANIUM = 152;
  
  // Arsenic
  FUEL_TYPE_ARSENIC = 153;
  
  // Selenium
  FUEL_TYPE_SELENIUM = 154;
  
  // Bromine
  FUEL_TYPE_BROMINE = 155;
  
  // Krypton
  FUEL_TYPE_KRYPTON = 156;
  
  // Rubidium
  FUEL_TYPE_RUBIDIUM = 157;
  
  // Strontium
  FUEL_TYPE_STRONTIUM = 158;
  
  // Yttrium
  FUEL_TYPE_YTTRIUM = 159;
  
  // Zirconium
  FUEL_TYPE_ZIRCONIUM = 160;
  
  // Niobium
  FUEL_TYPE_NIOBIUM = 161;
  
  // Molybdenum
  FUEL_TYPE_MOLYBDENUM = 162;
  
  // Technetium
  FUEL_TYPE_TECHNETIUM = 163;
  
  // Ruthenium
  FUEL_TYPE_RUTHENIUM = 164;
  
  // Rhodium
  FUEL_TYPE_RHODIUM = 165;
  
  // Palladium
  FUEL_TYPE_PALLADIUM = 166;
  
  // Silver
  FUEL_TYPE_SILVER = 167;
  
  // Cadmium
  FUEL_TYPE_CADMIUM = 168;
  
  // Indium
  FUEL_TYPE_INDIUM = 169;
  
  // Tin
  FUEL_TYPE_TIN = 170;
  
  // Antimony
  FUEL_TYPE_ANTIMONY = 171;
  
  // Tellurium
  FUEL_TYPE_TELLURIUM = 172;
  
  // Iodine
  FUEL_TYPE_IODINE = 173;
  
  // Xenon
  FUEL_TYPE_XENON = 174;
  
  // Cesium
  FUEL_TYPE_CESIUM = 175;
  
  // Barium
  FUEL_TYPE_BARIUM = 176;
  
  // Lanthanum
  FUEL_TYPE_LANTHANUM = 177;
  
  // Cerium
  FUEL_TYPE_CERIUM = 178;
  
  // Praseodymium
  FUEL_TYPE_PRASEODYMIUM = 179;
  
  // Neodymium
  FUEL_TYPE_NEODYMIUM = 180;
  
  // Promethium
  FUEL_TYPE_PROMETHIUM = 181;
  
  // Samarium
  FUEL_TYPE_SAMARIUM = 182;
  
  // Europium
  FUEL_TYPE_EUROPIUM = 183;
  
  // Gadolinium
  FUEL_TYPE_GADOLINIUM = 184;
  
  // Terbium
  FUEL_TYPE_TERBIUM = 185;
  
  // Dysprosium
  FUEL_TYPE_DYSPROSIUM = 186;
  
  // Holmium
  FUEL_TYPE_HOLMIUM = 187;
  
  // Erbium
  FUEL_TYPE_ERBIUM = 188;
  
  // Thulium
  FUEL_TYPE_THULIUM = 189;
  
  // Ytterbium
  FUEL_TYPE_YTTERBIUM = 190;
  
  // Lutetium
  FUEL_TYPE_LUTETIUM = 191;
  
  // Hafnium
  FUEL_TYPE_HAFNIUM = 192;
  
  // Tantalum
  FUEL_TYPE_TANTALUM = 193;
  
  // Tungsten
  FUEL_TYPE_TUNGSTEN = 194;
  
  // Rhenium
  FUEL_TYPE_RHENIUM = 195;
  
  // Osmium
  FUEL_TYPE_OSMIUM = 196;
  
  // Iridium
  FUEL_TYPE_IRIDIUM = 197;
  
  // Platinum
  FUEL_TYPE_PLATINUM = 198;
  
  // Gold
  FUEL_TYPE_GOLD = 199;
  
  // Mercury
  FUEL_TYPE_MERCURY = 200;
  
  // Thallium
  FUEL_TYPE_THALLIUM = 201;
  
  // Lead
  FUEL_TYPE_LEAD = 202;
  
  // Bismuth
  FUEL_TYPE_BISMUTH = 203;
  
  // Polonium
  FUEL_TYPE_POLONIUM = 204;
  
  // Astatine
  FUEL_TYPE_ASTATINE = 205;
  
  // Radon
  FUEL_TYPE_RADON = 206;
  
  // Francium
  FUEL_TYPE_FRANCIUM = 207;
  
  // Radium
  FUEL_TYPE_RADIUM = 208;
  
  // Actinium
  FUEL_TYPE_ACTINIUM = 209;
  
  // Protactinium
  FUEL_TYPE_PROTACTINIUM = 210;
  
  // Neptunium
  FUEL_TYPE_NEPTUNIUM = 211;
  
  // Americium
  FUEL_TYPE_AMERICIUM = 212;
  
  // Curium
  FUEL_TYPE_CURIUM = 213;
  
  // Berkelium
  FUEL_TYPE_BERKELIUM = 214;
  
  // Californium
  FUEL_TYPE_CALIFORNIUM = 215;
  
  // Einsteinium
  FUEL_TYPE_EINSTEINIUM = 216;
  
  // Fermium
  FUEL_TYPE_FERMIUM = 217;
  
  // Mendelevium
  FUEL_TYPE_MENDELEVIUM = 218;
  
  // Nobelium
  FUEL_TYPE_NOBELIUM = 219;
  
  // Lawrencium
  FUEL_TYPE_LAWRENCIUM = 220;
  
  // Rutherfordium
  FUEL_TYPE_RUTHERFORDIUM = 221;
  
  // Dubnium
  FUEL_TYPE_DUBNIUM = 222;
  
  // Seaborgium
  FUEL_TYPE_SEABORGIUM = 223;
  
  // Bohrium
  FUEL_TYPE_BOHRIUM = 224;
  
  // Hassium
  FUEL_TYPE_HASSIUM = 225;
  
  // Meitnerium
  FUEL_TYPE_MEITNERIUM = 226;
  
  // Darmstadtium
  FUEL_TYPE_DARMSTADTIUM = 227;
  
  // Roentgenium
  FUEL_TYPE_ROENTGENIUM = 228;
  
  // Copernicium
  FUEL_TYPE_COPERNICIUM = 229;
  
  // Nihonium
  FUEL_TYPE_NIHONIUM = 230;
  
  // Flerovium
  FUEL_TYPE_FLEROVIUM = 231;
  
  // Moscovium
  FUEL_TYPE_MOSCOVIUM = 232;
  
  // Livermorium
  FUEL_TYPE_LIVERMORIUM = 233;
  
  // Tennessine
  FUEL_TYPE_TENNESSINE = 234;
  
  // Oganesson
  FUEL_TYPE_OGANESSON = 235;
}
