{{- if .Values.cassandra.enabled }}
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: {{ .Values.cassandra.name }}
  namespace: {{ .Release.Namespace }}
spec:
  cassandra:
    serverVersion: {{ .Values.cassandra.version }}
    serverImage: cassandra:{{ .Values.cassandra.version }}
    datacenters:
    - metadata:
        name: dc1
      size: {{ .Values.cassandra.size }}
      resources:
        requests:
          cpu: {{ .Values.cassandra.resources.requests.cpu }}
          memory: {{ .Values.cassandra.resources.requests.memory }}
        limits:
          cpu: {{ .Values.cassandra.resources.limits.cpu }}
          memory: {{ .Values.cassandra.resources.limits.memory }}
      storageConfig:
        cassandraDataVolumeClaimSpec:
          storageClassName: {{ .Values.cassandra.storage.storageClass | default "" }}
          accessModes:
          - {{ .Values.cassandra.storage.accessMode }}
          resources:
            requests:
              storage: {{ .Values.cassandra.storage.size }}
      config:
        jvmOptions:
          heapSize: {{ .Values.cassandra.config.heap.heapSize }}
          newGenSize: {{ .Values.cassandra.config.heap.newGenSize }}
        {{- range .Values.cassandra.config.jvmOptions }}
        - {{ . | quote }}
        {{- end }}
  
  {{- if .Values.cassandra.reaper.enabled }}
  reaper:
    enabled: true
  {{- end }}
  
  {{- if .Values.cassandra.medusa.enabled }}
  medusa:
    enabled: true
    storageProperties:
      storageSecretRef:
        name: medusa-bucket-key
  {{- end }}
  
  {{- if .Values.cassandra.stargate.enabled }}
  stargate:
    size: {{ .Values.cassandra.stargate.replicas }}
  {{- end }}
{{- end }}

