# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Optional remote state — uncomment ONE backend block and set resource names from your account.
# OpenTofu/Terraform only allow a single backend stanza per configuration.
#
# --- AWS (S3 + DynamoDB lock) example ---
# terraform {
#   backend "s3" {
#     bucket         = "rice-tf-state-ACCOUNTID"
#     key            = "rice/dev/terraform.tfstate"
#     region         = "eu-west-1"
#     encrypt        = true
#     dynamodb_table = "rice-tf-locks"
#   }
# }
#
# --- GCP (GCS) example ---
# terraform {
#   backend "gcs" {
#     bucket = "rice-tf-state-PROJECT"
#     prefix = "dev"
#   }
# }
#
# --- Azure (azurerm) example ---
# terraform {
#   backend "azurerm" {
#     resource_group_name  = "rice-tf-state"
#     storage_account_name = "ricetfstate"
#     container_name         = "tfstate"
#     key                    = "dev.terraform.tfstate"
#   }
# }

terraform {
  backend "local" {
    path = ".terraform/state/rice-dev.tfstate"
  }
}