# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
terraform {
  required_version = ">= 1.6.0"
}

# Full module graph: `cd ..` (repo `.opentofu`) then `tofu init && tofu apply -var-file=environments/dev/terraform.tfvars`.
resource "terraform_data" "environment_marker" {
  input = {
    name = "dev"
    note = "Root stack: parent .opentofu/main.tf + modules/*"
  }
}