FROM octave:7.3.0

WORKDIR /app

COPY . .

# Install additional Octave packages if needed
RUN octave --eval "pkg install -forge io statistics signal"

EXPOSE 8080

CMD ["octave", "--no-gui", "main.m"]
