FROM ocaml/opam:alpine AS builder

WORKDIR /app

COPY dune-project *.opam ./
RUN opam install . --deps-only

COPY . .
RUN eval $(opam env) && dune build

FROM alpine:latest
RUN apk add --no-cache gmp

WORKDIR /app
COPY --from=builder /app/_build/default/bin/main.exe ./app

EXPOSE 8080

CMD ["./app"]
