FROM gcc:latest AS builder

WORKDIR /app
COPY . .

RUN g++ -o app *.cpp -std=c++17

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y libstdc++6 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 8080

CMD ["./app"]
