FROM sbtscala/scala-sbt:openjdk-17.0.2_1.7.1_3.2.0 AS builder

WORKDIR /app

COPY build.sbt project/ ./
RUN sbt update

COPY . .
RUN sbt assembly

FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=builder /app/target/scala-*/app-assembly-*.jar ./app.jar

EXPOSE 8080

CMD ["java", "-jar", "app.jar"]
