FROM haskell:9.4 AS builder

WORKDIR /app

COPY *.cabal cabal.project* ./
RUN cabal update && cabal build --dependencies-only

COPY . .
RUN cabal build && cabal install --installdir=/app/bin

FROM ubuntu:22.04
RUN apt-get update && apt-get install -y libgmp10 && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY --from=builder /app/bin/* ./

EXPOSE 8080

CMD ["./app"]
