//! CHIEF infra overlays: `let rice_*` / `let docker_*` string bindings for MASON Terraform and Docker.

use serde::Deserialize;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::Path;

/// Committed schema generated by `infra/scripts/mason-overlay-terraform-keys.sh` (also run inside `dagger call pour`).
const TERRAFORM_RICE_KEYS_JSON: &str =
    include_str!("../../../infra/proto/schema/terraform-rice-keys.json");

#[derive(Debug, Deserialize)]
struct TerraformRiceKeysFile {
    terraform_rice_variable_names: Vec<String>,
}

/// Names of root Terraform variables `rice_*` from MASON (`infra/terraform/cue/tf.cue`).
pub fn terraform_rice_variable_names() -> Vec<String> {
    let f: TerraformRiceKeysFile = serde_json::from_str(TERRAFORM_RICE_KEYS_JSON)
        .expect("infra/proto/schema/terraform-rice-keys.json must be valid JSON");
    f.terraform_rice_variable_names
}

/// Parse `let <ident> = "..."` lines (comments `#` and empty lines skipped). Values are string literals only.
pub fn parse_let_string_bindings(src: &str) -> Result<Vec<(String, String)>, String> {
    let mut out = Vec::new();
    for (lineno, line) in src.lines().enumerate() {
        let t = line.trim();
        if t.is_empty() || t.starts_with('#') {
            continue;
        }
        let Some(rest) = t.strip_prefix("let ") else {
            continue;
        };
        let rest = rest.trim();
        let Some(eq_pos) = rest.find('=') else {
            return Err(format!(
                "line {}: expected `=` in let-binding: {:?}",
                lineno + 1,
                t
            ));
        };
        let name = rest[..eq_pos].trim().to_string();
        if name.is_empty() {
            return Err(format!("line {}: empty binding name", lineno + 1));
        }
        let rhs = rest[eq_pos + 1..].trim();
        let rhs = rhs.strip_suffix(';').unwrap_or(rhs).trim();
        let Some(inner) = rhs
            .strip_prefix('"')
            .and_then(|s| s.strip_suffix('"'))
        else {
            return Err(format!(
                "line {}: expected string literal \"...\" after `=`, got {:?}",
                lineno + 1,
                rhs
            ));
        };
        out.push((name, inner.to_string()));
    }
    Ok(out)
}

/// Minimal required keys for a CHIEF `infra/terraform.rice` overlay (iteration 1).
pub const TERRAFORM_OVERLAY_REQUIRED: &[&str] = &[
    "rice_environment",
    "rice_domain",
    "rice_cloud_provider",
    "rice_github_org",
    "rice_github_repo",
];

/// Validate bindings: known Terraform names only; no duplicate keys; required keys present.
pub fn validate_terraform_overlay(
    bindings: &[(String, String)],
    allowed: &HashSet<String>,
) -> Vec<String> {
    let mut errs = Vec::new();
    let mut counts: HashMap<&str, usize> = HashMap::new();
    for (k, _) in bindings.iter() {
        if !k.starts_with("rice_") {
            errs.push(format!(
                "unknown overlay key `{k}` (terraform overlay must use rice_* names)"
            ));
            continue;
        }
        if !allowed.contains(k) {
            errs.push(format!(
                "key `{k}` is not a MASON root Terraform variable (regenerate schema if CUE changed)"
            ));
        }
        *counts.entry(k.as_str()).or_insert(0) += 1;
    }
    for (k, c) in counts.iter() {
        if *c > 1 {
            errs.push(format!("duplicate key `{k}` ({c} occurrences)"));
        }
    }
    let have: HashSet<&str> = bindings.iter().map(|(k, _)| k.as_str()).collect();
    for req in TERRAFORM_OVERLAY_REQUIRED {
        if !have.contains(*req) {
            errs.push(format!("missing required key `{req}`"));
        }
    }
    errs
}

/// Read `[project] name = "..."` from a CHIEF `bowl` file.
pub fn parse_bowl_name(bowl_src: &str) -> Result<String, String> {
    let mut in_project = false;
    for line in bowl_src.lines() {
        let t = line.trim();
        if t.starts_with('[') && t.ends_with(']') {
            in_project = t == "[project]";
            continue;
        }
        if !in_project {
            continue;
        }
        if let Some(rest) = t.strip_prefix("name") {
            let rest = rest.trim();
            if let Some(rest) = rest.strip_prefix('=') {
                let rest = rest.trim().trim_matches('"');
                if rest.is_empty() {
                    return Err("empty [project] name".into());
                }
                return Ok(rest.to_string());
            }
        }
    }
    Err("missing [project] name in bowl".into())
}

/// Patch `infra/gen/chief/docker_project.cue` from `custom/<slug>/bowl` + `infra/docker.rice`.
pub fn apply_docker_overlay(repo_root: &Path, project_slug: &str) -> Result<(), String> {
    let custom = repo_root.join("custom").join(project_slug);
    let bowl_path = custom.join("bowl");
    let rice_path = custom.join("infra/docker.rice");
    if !bowl_path.is_file() {
        return Err(format!("missing bowl: {}", bowl_path.display()));
    }
    if !rice_path.is_file() {
        return Err(format!("missing docker.rice: {}", rice_path.display()));
    }
    let bowl_src = fs::read_to_string(&bowl_path).map_err(|e| e.to_string())?;
    let project_name = parse_bowl_name(&bowl_src)?;
    let bowl_infra = crate::infra_rice::parse_bowl_infra_package(&bowl_src)?;
    let rice_src = fs::read_to_string(&rice_path).map_err(|e| e.to_string())?;
    let rice_import = crate::infra_rice::parse_infra_use_line(&rice_src)?;
    crate::infra_rice::validate_infra_rice_import(
        &bowl_infra,
        &rice_import,
        crate::infra_rice::FACET_DOCKER,
    )?;
    let cfg = crate::docker_rice::parse_docker_rice(&rice_src)?;
    let errs = crate::docker_rice::validate_docker_rice_profile(project_slug, &cfg);
    if !errs.is_empty() {
        return Err(errs.join("\n"));
    }
    let out = crate::docker_rice::render_project_cue(&project_name, &cfg);
    let project_cue = repo_root.join("infra/gen/chief/docker_project.cue");
    ensure_gen_dir(repo_root)?;
    fs::write(&project_cue, out).map_err(|e| e.to_string())?;
    let server_out = if cfg.server.otp.enabled
        || cfg.server.rpc.enabled
        || cfg.server.agent.enabled
        || cfg.server.docs.enabled
    {
        crate::server_rice::render_project_cue(&cfg.server)
    } else {
        crate::server_rice::render_disabled_stub()
    };
    fs::write(
        repo_root.join("infra/gen/chief/server_project.cue"),
        server_out,
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

/// Patch `infra/gen/chief/terraform_project.cue` from `custom/<slug>/bowl` + `infra/terraform.rice`.
pub fn apply_terraform_overlay(repo_root: &Path, project_slug: &str) -> Result<(), String> {
    let custom = repo_root.join("custom").join(project_slug);
    let bowl_path = custom.join("bowl");
    let rice_path = custom.join("infra/terraform.rice");
    if !bowl_path.is_file() {
        return Err(format!("missing bowl: {}", bowl_path.display()));
    }
    if !rice_path.is_file() {
        return Err(format!("missing terraform.rice: {}", rice_path.display()));
    }
    let bowl_src = fs::read_to_string(&bowl_path).map_err(|e| e.to_string())?;
    let _project_name = parse_bowl_name(&bowl_src)?;
    let bowl_infra = crate::infra_rice::parse_bowl_infra_package(&bowl_src)?;
    let rice_src = fs::read_to_string(&rice_path).map_err(|e| e.to_string())?;
    let rice_import = crate::infra_rice::parse_infra_use_line(&rice_src)?;
    crate::infra_rice::validate_infra_rice_import(
        &bowl_infra,
        &rice_import,
        crate::infra_rice::FACET_TERRAFORM,
    )?;
    let cfg = crate::terraform_rice::parse_terraform_rice(&rice_src)?;
    let bindings = cfg.to_bindings();
    let allowed: HashSet<String> = terraform_rice_variable_names().into_iter().collect();
    let errs = validate_terraform_overlay(&bindings, &allowed);
    if !errs.is_empty() {
        return Err(errs.join("\n"));
    }
    let out = crate::terraform_rice::render_terraform_project_cue(&cfg);
    let project_cue = repo_root.join("infra/gen/chief/terraform_project.cue");
    if let Some(parent) = project_cue.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(&project_cue, out).map_err(|e| e.to_string())?;
    Ok(())
}

/// Patch `infra/gen/chief/k8s_project.cue` from `custom/<slug>/bowl` + `infra/k8s.rice`.
pub fn apply_k8s_overlay(repo_root: &Path, project_slug: &str) -> Result<(), String> {
    let custom = repo_root.join("custom").join(project_slug);
    let bowl_path = custom.join("bowl");
    let rice_path = custom.join("infra/k8s.rice");
    if !bowl_path.is_file() {
        return Err(format!("missing bowl: {}", bowl_path.display()));
    }
    if !rice_path.is_file() {
        return Err(format!("missing k8s.rice: {}", rice_path.display()));
    }
    let bowl_src = fs::read_to_string(&bowl_path).map_err(|e| e.to_string())?;
    let _project_name = parse_bowl_name(&bowl_src)?;
    let bowl_infra = crate::infra_rice::parse_bowl_infra_package(&bowl_src)?;
    let rice_src = fs::read_to_string(&rice_path).map_err(|e| e.to_string())?;
    let rice_import = crate::infra_rice::parse_infra_use_line(&rice_src)?;
    crate::infra_rice::validate_infra_rice_import(
        &bowl_infra,
        &rice_import,
        crate::infra_rice::FACET_K8S,
    )?;
    let cfg = crate::k8s_rice::parse_k8s_rice(&rice_src)?;
    let errs = crate::k8s_rice::validate_k8s_rice_profile(project_slug, &cfg);
    if !errs.is_empty() {
        return Err(errs.join("\n"));
    }
    let out = crate::k8s_rice::render_project_cue(project_slug, &cfg);
    let project_cue = repo_root.join("infra/gen/chief/k8s_project.cue");
    if let Some(parent) = project_cue.parent() {
        fs::create_dir_all(parent).map_err(|e| e.to_string())?;
    }
    fs::write(&project_cue, out).map_err(|e| e.to_string())?;
    Ok(())
}

fn ensure_gen_dir(repo_root: &Path) -> Result<(), String> {
    let d = repo_root.join("infra/gen/chief");
    fs::create_dir_all(&d).map_err(|e| e.to_string())
}

/// Patch `infra/gen/chief/docs_project.cue` and PlantUML assets from `infra/docs.rice`.
pub fn apply_docs_overlay(repo_root: &Path, project_slug: &str) -> Result<(), String> {
    ensure_gen_dir(repo_root)?;
    let rice_path = repo_root
        .join("custom")
        .join(project_slug)
        .join("infra/docs.rice");
    let out = if rice_path.is_file() {
        let bowl_path = repo_root.join("custom").join(project_slug).join("bowl");
        let bowl_src = fs::read_to_string(&bowl_path).map_err(|e| e.to_string())?;
        let bowl_infra = crate::infra_rice::parse_bowl_infra_package(&bowl_src)?;
        let rice_src = fs::read_to_string(&rice_path).map_err(|e| e.to_string())?;
        let rice_import = crate::infra_rice::parse_infra_use_line(&rice_src)?;
        crate::infra_rice::validate_infra_rice_import(
            &bowl_infra,
            &rice_import,
            crate::infra_rice::FACET_DOCS,
        )?;
        let cfg = crate::docs_rice::parse_docs_rice(&rice_src)?;
        crate::docs_rice::write_diagram_assets(repo_root, &cfg)?;
        crate::docs_rice::render_project_cue(&cfg)
    } else {
        crate::docs_rice::render_disabled_stub()
    };
    fs::write(
        repo_root.join("infra/gen/chief/docs_project.cue"),
        out,
    )
    .map_err(|e| e.to_string())?;
    Ok(())
}

/// Patch `infra/gen/chief/frontend_project.cue` and `frontend/lib/generated/rice_config.dart`.
pub fn apply_frontend_overlay(repo_root: &Path, project_slug: &str) -> Result<(), String> {
    ensure_gen_dir(repo_root)?;
    let site_rice = repo_root
        .join("custom")
        .join(project_slug)
        .join("frontend/site.rice");
    if !site_rice.is_file() {
        let stub = crate::frontend_rice::render_disabled_stub();
        fs::write(
            repo_root.join("infra/gen/chief/frontend_project.cue"),
            stub,
        )
        .map_err(|e| e.to_string())?;
        return Ok(());
    }
    let bowl_path = repo_root.join("custom").join(project_slug).join("bowl");
    let bowl_src = fs::read_to_string(&bowl_path).map_err(|e| e.to_string())?;
    let bowl_infra = crate::infra_rice::parse_bowl_infra_package(&bowl_src)?;
    let rice_src = fs::read_to_string(&site_rice).map_err(|e| e.to_string())?;
    let rice_import = crate::infra_rice::parse_infra_use_line(&rice_src)?;
    crate::infra_rice::validate_infra_rice_import(
        &bowl_infra,
        &rice_import,
        crate::infra_rice::FACET_FRONTEND,
    )?;
    let cfg = crate::frontend_rice::parse_frontend_rice(&rice_src)?;
    let out = crate::frontend_rice::render_project_cue(&cfg);
    fs::write(
        repo_root.join("infra/gen/chief/frontend_project.cue"),
        out,
    )
    .map_err(|e| e.to_string())?;
    let project_dir = repo_root.join("custom").join(project_slug);
    crate::frontend_rice::write_dart_config(&project_dir, &cfg)?;
    Ok(())
}

/// Resolve CHIEF project slug — requires `CHIEF_PROJECT` for overlay apply / gen.
pub fn chief_project_slug(_repo_root: &Path) -> Option<String> {
    std::env::var("CHIEF_PROJECT")
        .ok()
        .map(|p| p.trim().to_string())
        .filter(|p| !p.is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_two_lets() {
        let s = r#"
# c
let rice_domain = "a.example"
let rice_environment = "dev";
"#;
        let v = parse_let_string_bindings(s).unwrap();
        assert_eq!(
            v,
            vec![
                ("rice_domain".into(), "a.example".into()),
                ("rice_environment".into(), "dev".into()),
            ]
        );
    }

    #[test]
    fn parse_bowl_project_name() {
        let s = "[project]\nname = \"code-rice.com\"\n";
        assert_eq!(parse_bowl_name(s).unwrap(), "code-rice.com");
    }

    #[test]
    fn parse_bowl_requires_infra_package() {
        let s = "[project]\nname = \"egos.app\"\n";
        assert!(crate::infra_rice::parse_bowl_infra_package(s).is_err());
    }

    #[test]
    fn validate_rejects_unknown_rice_key() {
        let allowed: HashSet<_> = terraform_rice_variable_names()
            .into_iter()
            .collect();
        let bindings = vec![("rice_not_a_var".into(), "x".into())];
        let e = validate_terraform_overlay(&bindings, &allowed);
        assert!(e.iter().any(|m| m.contains("not a MASON")));
    }
}
