package k8s

// _tool.cue — cue cmd genK8s (orchestrated from infra/_tool.cue).
// Load: infra/k8s/_tool.cue + infra/k8s/cue/**/*.cue + infra/gen/chief/k8s_project.cue

import (
	"encoding/yaml"
	"strings"
	"tool/file"
)

_generatedHeader: """
	# Code generated by MASON — cue cmd genK8s. DO NOT EDIT.

	"""

command: genK8s: {
	for path, docs in allGeneratedFiles {
		let safe = strings.Replace(path, "/", "-", -1)
		"write-\(safe)": file.Create & {
			filename: path
			contents: _generatedHeader + strings.Join([ for d in docs {
				strings.TrimSpace(yaml.Marshal(d))
			}], "\n---\n") + "\n"
			permissions: 0o644
		}
	}
}
