# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
locals {
  rice_deployments = var.rice_deployments
}

module "clusters" {
  for_each = local.rice_deployments
  source   = "./modules/clusters"

  rice_environment         = var.rice_environment
  rice_cloud_provider      = each.value.cloud
  rice_region              = each.value.region
  rice_vpc_cidr            = each.value.vpc_cidr
  rice_k8s_cluster_name    = var.rice_k8s_cluster_name
  rice_availability_zones  = var.rice_availability_zones
  rice_enable_gpu          = var.rice_enable_gpu
  rice_gpu_instance_type   = var.rice_gpu_instance_type
}

module "databases" {
  for_each = local.rice_deployments
  source   = "./modules/databases"

  rice_environment       = var.rice_environment
  rice_cloud_provider    = each.value.cloud
  rice_region            = each.value.region
  rice_db_instance_class = var.rice_db_instance_class
}

module "auth" {
  source = "./modules/auth"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_github_org     = var.rice_github_org
  rice_github_repo    = var.rice_github_repo
}

module "certificates" {
  source = "./modules/certificates"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_domain         = var.rice_domain
}

module "routes" {
  source = "./modules/routes"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_domain         = var.rice_domain
}

module "stores" {
  for_each = local.rice_deployments
  source   = "./modules/stores"

  rice_environment    = var.rice_environment
  rice_cloud_provider = each.value.cloud
  rice_region         = each.value.region
}

module "kubernetes" {
  for_each = local.rice_deployments
  source   = "./modules/kubernetes"

  rice_environment      = var.rice_environment
  rice_cloud_provider     = each.value.cloud
  rice_region             = each.value.region
  rice_k8s_cluster_name   = var.rice_k8s_cluster_name
}