# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_tf_backend" {
  value       = var.rice_tf_backend
  description = "Operator hint for state storage (local | s3 | gcs | azurerm); backend blocks live under environments/*/backend.tf."
}

output "rice_environment" {
  value       = var.rice_environment
  description = "Active environment label."
}

output "rice_cloud_provider" {
  value       = var.rice_cloud_provider
  description = "Primary cloud selection."
}

output "rice_k8s_endpoint" {
  value       = format("https://api.%s.$${var.rice_region}.$${var.rice_cloud_provider}.rice-stub.invalid:6443", replace(var.rice_k8s_cluster_name, "/", "-"))
  description = "Synthetic API hostname until the clusters module exports a real control plane URL."
}

output "rice_registry_url" {
  value       = "$${var.rice_registry}/$${var.rice_github_org}/$${var.rice_github_repo}"
  description = "Default OCI image prefix for CI pushes."
}

output "rice_db_connection_string" {
  value       = length(module.databases) > 0 ? format("postgresql://rice:CHANGEME@%s-%s-pg.rice-stub.invalid:5432/rice_$${var.rice_environment}?sslmode=require", values(module.databases)[0].probe.cloud_provider, values(module.databases)[0].probe.region) : ""
  sensitive   = true
  description = "Placeholder JDBC-style URL from databases probe; replace when RDS/Cloud SQL/... exists."
}

output "rice_kms_key_id" {
  value       = format("alias/rice-%s-%s-kms-stub", var.rice_environment, var.rice_cloud_provider)
  description = "KMS alias placeholder; wire to module.auth when cloud KMS keys are created."
}

output "rice_nats_lb_ip" {
  value       = format("nat-lb-%s-%s-pending", var.rice_environment, var.rice_region)
  description = "Placeholder until routes/stores modules publish a messaging load balancer hostname or IP."
}

output "rice_harbor_hostname" {
  value       = "harbor.$${var.rice_domain}"
  description = "Default Harbor hostname pattern (adjust when Harbor module exists)."
}

output "module_probes" {
  value = {
    clusters     = { for k, m in module.clusters : k => m.probe }
    databases    = { for k, m in module.databases : k => m.probe }
    auth         = module.auth.probe
    certificates = module.certificates.probe
    routes       = module.routes.probe
    stores       = { for k, m in module.stores : k => m.probe }
    kubernetes   = { for k, m in module.kubernetes : k => m.probe }
  }
  description = "Stub probes from each module — replace with real outputs as implementations land."
}