# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Root-level provider aliases — detailed blocks also live under `providers/{aws,gcp,azure}/`.
# Kubernetes / Helm / kubectl / sops providers are declared in required_providers; configure them when modules need cluster access.

locals {
  kubeconfig = pathexpand(var.rice_kubeconfig_path)
}

provider "kubernetes" {
  config_path = local.kubeconfig
}

provider "helm" {
  kubernetes {
    config_path = local.kubeconfig
  }
}

provider "kubectl" {
  config_path = local.kubeconfig
}

locals {
  enable_aws   = contains(var.rice_enabled_clouds, "aws")
  enable_gcp   = contains(var.rice_enabled_clouds, "gcp")
  enable_azure = contains(var.rice_enabled_clouds, "azure")
}

provider "aws" {
  region = var.rice_aws_region

  dynamic "assume_role" {
    for_each = var.rice_aws_assume_role_arn != "" ? [1] : []
    content {
      role_arn = var.rice_aws_assume_role_arn
    }
  }
}

provider "google" {
  project               = var.rice_gcp_project_id
  region                = var.rice_gcp_region
  user_project_override = true
}

provider "azurerm" {
  features {}

  subscription_id = var.rice_azure_subscription_id != "" ? var.rice_azure_subscription_id : null
  tenant_id       = var.rice_azure_tenant_id != "" ? var.rice_azure_tenant_id : null
}