# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" {
  type        = string
  description = "Deployment slice: dev | stag | prod."
  validation {
    condition     = contains(["dev", "stag", "prod"], var.rice_environment)
    error_message = "rice_environment must be dev, stag, or prod."
  }
}

variable "rice_cloud_provider" {
  type        = string
  description = "Primary cloud: aws | gcp | azure | all (multi-cloud planning)."
  validation {
    condition     = contains(["aws", "gcp", "azure", "all"], var.rice_cloud_provider)
    error_message = "rice_cloud_provider must be aws, gcp, azure, or all."
  }
}

variable "rice_github_org" {
  type        = string
  description = "GitHub org for CI / OIDC (required for auth module wiring)."
}

variable "rice_github_repo" {
  type        = string
  description = "GitHub repository name under rice_github_org."
}

variable "rice_domain" {
  type        = string
  description = "Public DNS apex for ingress / ACM / managed certs."
}

variable "rice_k8s_cluster_name" {
  type        = string
  description = "Logical Kubernetes cluster name (tags / resource names)."
}

variable "rice_db_instance_class" {
  type        = string
  description = "Default DB instance / tier class per provider."
}

variable "rice_registry" {
  type        = string
  description = "OCI registry host for images (default GHCR)."
  default     = "ghcr.io"
}

variable "rice_region" {
  type        = string
  description = "Primary region slug for the active cloud (see also cloud-specific vars)."
}

variable "rice_availability_zones" {
  type        = list(string)
  description = "AZs for HA subnets / node groups."
}

variable "rice_vpc_cidr" {
  type        = string
  description = "IPv4 CIDR for workload VPC / equivalent."
  default     = "10.0.0.0/16"
}

variable "rice_enable_gpu" {
  type        = bool
  description = "Whether GPU node pools / instance types are enabled."
  default     = false
}

variable "rice_gpu_instance_type" {
  type        = string
  description = "GPU-capable instance type when rice_enable_gpu is true."
  default     = ""
}

variable "rice_aws_region" {
  type        = string
  description = "AWS region for provider + regional resources."
}

variable "rice_aws_assume_role_arn" {
  type        = string
  description = "Optional IAM role for provider assume_role."
  default     = ""
}

variable "rice_gcp_project_id" {
  type        = string
  description = "GCP project ID (replace placeholder before applying GCP resources)."
}

variable "rice_gcp_region" {
  type        = string
  description = "Default GCP region."
}

variable "rice_azure_subscription_id" {
  type        = string
  description = "Azure subscription ID (optional with az login / OIDC)."
  default     = ""
}

variable "rice_azure_tenant_id" {
  type        = string
  description = "Azure AD tenant ID (optional in many flows)."
  default     = ""
}

variable "rice_tf_backend" {
  type        = string
  description = "Hint for operators: local | s3 | gcs | azurerm (backend blocks live under environments/*/backend.tf)."
  default     = "local"
}

variable "rice_kubeconfig_path" {
  type        = string
  description = "Kubeconfig path for kubernetes / helm / kubectl providers (use an absolute path in CI)."
  default     = "~/.kube/config"
}

variable "rice_enabled_clouds" {
  type        = list(string)
  description = "Clouds active in this stack (aws, gcp, azure)."
  default     = ["aws"]
}

variable "rice_primary_cloud" {
  type        = string
  description = "Primary cloud for singleton modules and default routing."
  default     = "aws"
}

variable "rice_regions" {
  type = object({
    aws   = optional(list(string), [])
    gcp   = optional(list(string), [])
    azure = optional(list(string), [])
  })
  description = "Region lists per cloud (CHIEF regions set block)."
  default = {
    aws   = []
    gcp   = []
    azure = []
  }
}

variable "rice_regions_aws" {
  type        = list(string)
  description = "AWS regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_regions_gcp" {
  type        = list(string)
  description = "GCP regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_regions_azure" {
  type        = list(string)
  description = "Azure regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_deployments" {
  type = map(object({
    cloud    = string
    region   = string
    vpc_cidr = string
  }))
  description = "Multi-cloud × multi-region deployment matrix (keys: cloud:region)."
}