// Mapowanie ikon lucide-react na Material Symbols
const iconMap = {
  'Heart': 'material-symbols:favorite',
  'ShoppingBag': 'material-symbols:shopping-bag',
  'ShoppingCart': 'material-symbols:shopping-cart',
  'Menu': 'material-symbols:menu',
  'X': 'material-symbols:close',
  'Mail': 'material-symbols:mail',
  'Phone': 'material-symbols:phone',
  'MapPin': 'material-symbols:location-on',
  'Gift': 'material-symbols:card-giftcard',
  'Plus': 'material-symbols:add',
  'Minus': 'material-symbols:remove',
  'Users': 'material-symbols:people',
  'UserPlus': 'material-symbols:person-add',
  'DollarSign': 'material-symbols:attach-money',
  'TrendingUp': 'material-symbols:trending-up',
  'TrendingDown': 'material-symbols:trending-down',
  'Calculator': 'material-symbols:calculate',
  'FileText': 'material-symbols:description',
  'AlertCircle': 'material-symbols:error',
  'Edit2': 'material-symbols:edit',
  'Package': 'material-symbols:inventory-2',
  'Download': 'material-symbols:download',
  'Calendar': 'material-symbols:calendar-today',
  'Bell': 'material-symbols:notifications',
  'Search': 'material-symbols:search',
  'Settings': 'material-symbols:settings',
  'User': 'material-symbols:person',
  'Trash2': 'material-symbols:delete',
  'Eye': 'material-symbols:visibility',
  'CheckCircle': 'material-symbols:check-circle',
  'Clock': 'material-symbols:schedule',
  'ArrowLeft': 'material-symbols:arrow-back',
  'ArrowRight': 'material-symbols:arrow-forward',
  'Home': 'material-symbols:home',
  'Star': 'material-symbols:star',
  'ExternalLink': 'material-symbols:open-in-new',
  'Upload': 'material-symbols:upload',
  'Tag': 'material-symbols:local-offer',
  'Coffee': 'material-symbols:local-cafe',
  'Image': 'material-symbols:image',
  'Save': 'material-symbols:save',
  'Filter': 'material-symbols:filter-list',
  'SlidersHorizontal': 'material-symbols:tune',
  'Grid': 'material-symbols:grid-view',
  'List': 'material-symbols:list',
  'CreditCard': 'material-symbols:credit-card',
  'Shield': 'material-symbols:security',
  'Cat': 'material-symbols:pets',
  'Check': 'material-symbols:check',
  'Lock': 'material-symbols:lock',
  'Truck': 'material-symbols:local-shipping',
};

console.log('Icon mapping created. Use this to replace icons in files.');

