syntax = "proto3";

package chainrice.chainrice.messages;

import "amino/amino.proto";
import "gogoproto/gogo.proto";
import "messages/blockchain/validator.proto";

option go_package = "github.com/chainrice/chainrice/x/chainrice/types";

// Params defines the parameters for the module.
message Params {
  option (amino.name) = "chainrice/x/chainrice/Params";
  option (gogoproto.equal) = true;
}

// GenesisState defines the chainrice module's genesis state.
message GenesisState {
  // params defines all the parameters of the module.
  Params params = 1 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  
  // validators defines the initial validators
  repeated Validator validators = 2 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
  
  // bitcoin_balances defines initial Bitcoin balances
  repeated BitcoinBalance bitcoin_balances = 3 [
    (gogoproto.nullable) = false,
    (amino.dont_omitempty) = true
  ];
}
