"""Quantum simulations: Qiskit (circuits, Aer), PennyLane (hybrid), JAX compute.

Exports circuits (create_circuit, bell_circuit, ghz_circuit, compile_circuit, etc.), simulate
(run_simulation, get_counts, get_statevector, noise models), hybrid (variational_circuit,
create_qnode, optimize_variational, quantum_embedding), compute (JAX jit, grad, vmap, expectation_value),
and models (CircuitConfig, ResultSummary, JobStatus, etc.). Optional extra: sim. English only.
"""

from sim.circuits import (
    add_cnot,
    add_hadamard,
    add_measurement,
    add_rotation,
    add_single_qubit_gate,
    bell_circuit,
    compile_circuit,
    create_circuit,
    depth,
    gate_count,
    get_measurement_ops,
    ghz_circuit,
    optimize_circuit,
    transpile_to_basis,
)
from sim.models import (
    CircuitConfig,
    HybridConfig,
    JAXComputeConfig,
    JobInfo,
    JobStatus,
    MeasurementOutcome,
    MeasurementResults,
    PytreeStructure,
    ResultSummary,
    SimulatorConfig,
)
from sim.simulate import (
    build_noise_model,
    get_aer_simulator,
    get_counts,
    get_density_matrix_simulator,
    get_statevector_simulator,
    get_statevector,
    get_unitary,
    job_status,
    run_circuit,
    run_sync,
    simulator_with_noise,
)
from sim.hybrid import (
    cost_fn,
    create_qnode,
    default_qubit_device,
    gradient_circuit,
    hybrid_classifier_layer,
    optimize_variational,
    parameter_shift_gradient,
    quantum_embedding,
    variational_circuit,
    vqe_ansatz,
)
from sim.compute import (
    check_gpu_availability,
    compute_gradient,
    configure_jax,
    expectation_value,
    grad_fun,
    jax_array,
    jax_zeros,
    jit,
    jit_compile,
    jit_fun,
    physics_step,
    quantum_expectation,
    value_and_grad,
    vectorize_function,
    vmap_fun,
    xla_compile,
)

__all__ = [
    "add_cnot",
    "add_hadamard",
    "add_measurement",
    "add_rotation",
    "add_single_qubit_gate",
    "bell_circuit",
    "compile_circuit",
    "create_circuit",
    "depth",
    "gate_count",
    "get_measurement_ops",
    "ghz_circuit",
    "optimize_circuit",
    "transpile_to_basis",
    "build_noise_model",
    "get_aer_simulator",
    "get_counts",
    "get_density_matrix_simulator",
    "get_statevector_simulator",
    "get_statevector",
    "get_unitary",
    "job_status",
    "run_circuit",
    "run_sync",
    "simulator_with_noise",
    "cost_fn",
    "create_qnode",
    "default_qubit_device",
    "gradient_circuit",
    "hybrid_classifier_layer",
    "optimize_variational",
    "parameter_shift_gradient",
    "quantum_embedding",
    "variational_circuit",
    "vqe_ansatz",
    "CircuitConfig",
    "HybridConfig",
    "JAXComputeConfig",
    "JobInfo",
    "JobStatus",
    "MeasurementOutcome",
    "MeasurementResults",
    "PytreeStructure",
    "ResultSummary",
    "SimulatorConfig",
    "check_gpu_availability",
    "compute_gradient",
    "configure_jax",
    "expectation_value",
    "grad_fun",
    "jax_array",
    "jax_zeros",
    "jit",
    "jit_compile",
    "jit_fun",
    "physics_step",
    "quantum_expectation",
    "value_and_grad",
    "vectorize_function",
    "vmap_fun",
    "xla_compile",
]
