# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_aws_region_effective" {
  value       = var.rice_aws_region
  description = "Region wired into the AWS provider."
}