# Generated — cue cmd genTerraform (MASON infra/terraform/cue)
# CHIEF overlay: custom/*/infra/terraform.rice → infra/gen/chief/terraform_project.cue
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "aws" {
  region = var.rice_aws_region

  dynamic "assume_role" {
    for_each = var.rice_aws_assume_role_arn != "" ? [1] : []
    content {
      role_arn = var.rice_aws_assume_role_arn
    }
  }

  default_tags {
    tags = {
      Project     = "rice"
      Environment = var.rice_environment
      ManagedBy   = "opentofu"
    }
  }
}