package package

languageDart: {
  manager:      "pub"
  manifestFile: "pubspec.yaml"
  ecosystem:    "dart"
  manifests: [
    "frontend/browser/pubspec.yaml",
    "frontend/client/pubspec.yaml",
    "frontend/content/pubspec.yaml",
    "frontend/lang/pubspec.yaml",
    "frontend/model/pubspec.yaml",
    "frontend/pubspec.yaml",
    "frontend/rule/pubspec.yaml",
    "frontend/lang/slang.yaml",
  ]

  defaults: {
    version: "0.1.0"
    sdk:     ">=3.0.0 <4.0.0"
  }

  sharedDependencies: {
    flutter:     "sdk:flutter"
    riverpod:    "^2.5.1"
    freezed_annotation: "^2.4.4"
    json_annotation: "^4.9.0"
  }

  projects: {
    root:    {path: "frontend/pubspec.yaml",          name: "rice_frontend",          deps: ["flutter", "riverpod"]}
    browser: {path: "frontend/browser/pubspec.yaml",  name: "rice_frontend_browser",  deps: ["flutter", "riverpod"]}
    client:  {path: "frontend/client/pubspec.yaml",   name: "rice_frontend_client",   deps: ["flutter", "riverpod", "json_annotation"]}
    content: {path: "frontend/content/pubspec.yaml",  name: "rice_frontend_content",  deps: ["flutter", "freezed_annotation"]}
    lang:    {path: "frontend/lang/pubspec.yaml",     name: "rice_frontend_lang",     deps: ["flutter", "json_annotation"]}
    model:   {path: "frontend/model/pubspec.yaml",    name: "rice_frontend_model",    deps: ["flutter", "freezed_annotation", "json_annotation"]}
    rule:    {path: "frontend/rule/pubspec.yaml",     name: "rice_frontend_rule",     deps: ["flutter", "riverpod"]}
  }

  constraints: {
    requiredSharedDeps: [for _, project in projects for dep in project.deps {sharedDependencies[dep]}]
  }

  render: {
    pubspecYamls: [
      {name: "root",    path: projects.root.path,    kind: "pubspec", data: {name: projects.root.name,    version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.root.deps,    dependencyVersions: sharedDependencies}},
      {name: "browser", path: projects.browser.path, kind: "pubspec", data: {name: projects.browser.name, version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.browser.deps, dependencyVersions: sharedDependencies}},
      {name: "client",  path: projects.client.path,  kind: "pubspec", data: {name: projects.client.name,  version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.client.deps,  dependencyVersions: sharedDependencies}},
      {name: "content", path: projects.content.path, kind: "pubspec", data: {name: projects.content.name, version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.content.deps, dependencyVersions: sharedDependencies}},
      {name: "lang",    path: projects.lang.path,    kind: "pubspec", data: {name: projects.lang.name,    version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.lang.deps,    dependencyVersions: sharedDependencies}},
      {name: "model",   path: projects.model.path,   kind: "pubspec", data: {name: projects.model.name,   version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.model.deps,   dependencyVersions: sharedDependencies}},
      {name: "rule",    path: projects.rule.path,    kind: "pubspec", data: {name: projects.rule.name,    version: defaults.version, description: "Generated by MASON package model", environment: {sdk: defaults.sdk}, dependencies: projects.rule.deps,    dependencyVersions: sharedDependencies}},
    ]
  }

  emitFiles: [{
    path: "frontend/lang/slang.yaml"
    content: #"""
base_locale: en
fallback_strategy: base_locale
input_directory: lib/i18n
output_directory: lib/i18n
translate_var: t
string_interpolation: dart
"""#
  }]
}
