[package]
name = "clerk-private"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "RICE ZK layer — Groth16, BN254/BLS12-381 circuits, proof lifecycle"

[lib]
path = "src/lib.rs"

[dependencies]
clerk-util = { path = "../util" }
ark-bls12-381.workspace = true
ark-bn254.workspace = true
ark-crypto-primitives.workspace = true
ark-ec.workspace = true
ark-ff.workspace = true
ark-groth16.workspace = true
ark-serialize.workspace = true
ark-relations.workspace = true
ark-snark.workspace = true
ark-std.workspace = true
thiserror.workspace = true
rand.workspace = true
