import { AppRoute } from "@/types/routes/routes";

export const docsRoutes: AppRoute[] = [
  {
    path: "/docs",
    label: "Dokumentacja główna",
    slug: "index",
    file: "index.md",
    title: "Dokumentacja główna",
  },
  {
    path: "/docs/roadmap",
    label: "Roadmapa",
    slug: "roadmap",
    file: "roadmap.md",
    title: "Roadmapa",
  },
  {
    path: "/docs/faq",
    label: "FAQ",
    slug: "faq",
    file: "faq.md",
    title: "FAQ",
  },
  {
    path: "/docs/support",
    label: "Wsparcie",
    slug: "support",
    file: "support.md",
    title: "Wsparcie",
  },
  {
    path: "/docs/sjsc",
    label: "SJSC",
    slug: "sjsc",
    file: "company/simple-joint-stock-company(SJSC).md",
    title: "SJSC",
  },
  {
    path: "/docs/llc",
    label: "LLC",
    slug: "llc",
    file: "company/limited-liability-company(LLC).md",
    title: "LLC",
  },
  {
    path: "/docs/npf",
    label: "NPF",
    slug: "npf",
    file: "company/non-profit-foundation(NPF).md",
    title: "NPF",
  },
  {
    path: "/docs/casp-license",
    label: "Casp License",
    slug: "casp-license",
    file: "compliance/casp-license.md",
    title: "Casp License",
  },
  {
    path: "/docs/export-crypto",
    label: "Export Crypto",
    slug: "export-crypto",
    file: "compliance/export-crypto.md",
    title: "Export Crypto",
  },
  {
    path: "/docs/iso-27001",
    label: "ISO 27001",
    slug: "iso-27001",
    file: "compliance/iso-27001.md",
    title: "ISO 27001",
  },
  {
    path: "/docs/iso-27701",
    label: "ISO 27701",
    slug: "iso-27701",
    file: "compliance/iso-27701.md",
    title: "ISO 27701",
  },
  {
    path: "/docs/pci-compliance",
    label: "PCI Compliance",
    slug: "pci-compliance",
    file: "compliance/pci-compliance.md",
    title: "PCI Compliance",
  },
  {
    path: "/docs/security-audit",
    label: "Security Audit",
    slug: "security-audit",
    file: "compliance/security-audit.md",
    title: "Security Audit",
  },
  {
    path: "/docs/ssl-info",
    label: "SSL Info",
    slug: "ssl-info",
    file: "compliance/ssl-info.md",
    title: "SSL Info",
  },
  {
    path: "/docs/culture",
    label: "Kultura",
    slug: "culture",
    file: "constitution/culture.md",
    title: "Kultura",
  },
  {
    path: "/docs/dyplomacy",
    label: "Dyplomacja",
    slug: "dyplomacy",
    file: "constitution/dyplomacy.md",
    title: "Dyplomacja",
  },
  {
    path: "/docs/education",
    label: "Edukacja",
    slug: "education",
    file: "constitution/education.md",
    title: "Edukacja",
  },
  {
    path: "/docs/money",
    label: "Pieniadze",
    slug: "money",
    file: "constitution/money.md",
    title: "Pieniadze",
  },
  {
    path: "/docs/religion",
    label: "Religia",
    slug: "religion",
    file: "constitution/religion.md",
    title: "Religia",
  },
  {
    path: "/docs/war",
    label: "Wojna",
    slug: "war",
    file: "constitution/war.md",
    title: "Wojna",
  },
  {
    path: "/docs/aml",
    label: "AML",
    slug: "aml",
    file: "policies/aml.md",
    title: "AML",
  },
  {
    path: "/docs/cookies-consent",
    label: "Cookies Consent",
    slug: "cookies-consent",
    file: "policies/cookies-consent.md",
    title: "Cookies Consent",
  },
  {
    path: "/docs/disclaimer",
    label: "Disclaimer",
    slug: "disclaimer",
    file: "policies/disclaimer.md",
    title: "Disclaimer",
  },
  {
    path: "/docs/dpa",
    label: "DPA",
    slug: "dpa",
    file: "policies/dpa.md",
    title: "DPA",
  },
  {
    path: "/docs/gdpr-impact",
    label: "GDPR Impact",
    slug: "gdpr-impact",
    file: "policies/gdpr-impact.md",
    title: "GDPR Impact",
  },
  {
    path: "/docs/kyc",
    label: "KYC",
    slug: "kyc",
    file: "policies/kyc.md",
    title: "KYC",
  },
  {
    path: "/docs/privacy",
    label: "privacy",
    slug: "privacy",
    file: "policies/privacy.md",
    title: "privacy",
  },
  {
    path: "/docs/processors-list",
    label: "Processors List",
    slug: "processors-list",
    file: "policies/processors-list.md",
    title: "Processors List",
  },
  {
    path: "/docs/terms",
    label: "Terms",
    slug: "terms",
    file: "policies/terms.md",
    title: "Terms",
  },
  {
    path: "/docs/token-whitepaper",
    label: "Token Whitepaper",
    slug: "token-whitepaper",
    file: "policies/token-whitepaper.md",
    title: "Token Whitepaper",
  },
  {
    path: "/docs/partner-contract",
    label: "Umowa partnerska",
    slug: "partner-contract",
    file: "webapp/partner-contract.md",
    title: "Token Whitepaper",
  },
  {
    path: "/docs/partner-panel-tos",
    label: "Token Whitepaper",
    slug: "partner-panel-tos",
    file: "webapp/partner-panel-tos.md",
    title: "Token Whitepaper",
  },
  {
    path: "/docs/user-privacy",
    label: "Token Whitepaper",
    slug: "user-privacy",
    file: "webapp/user-privacy.md",
    title: "Token Whitepaper",
  },
  {
    path: "/docs/user-tos",
    label: "Token Whitepaper",
    slug: "user-tos",
    file: "webapp/user-tos.md",
    title: "Token Whitepaper",
  },
];
