apiVersion: v2
name: knative
description: Knative Serving for serverless HTTP/gRPC workloads
type: application
version: 1.0.0
appVersion: "1.13"

dependencies:
  - name: knative-serving
    version: "1.13.0"
    repository: "https://knative.github.io/knative-operator"
    condition: knative.enabled

