// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: chainrice/chainrice/v1/accounting.proto

package types

import (
	fmt "fmt"
	math "math"

	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Invoice represents a business invoice
type Invoice struct {
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InvoiceNumber    string                 `protobuf:"bytes,2,opt,name=invoice_number,json=invoiceNumber,proto3" json:"invoice_number,omitempty"`
	VendorName       string                 `protobuf:"bytes,3,opt,name=vendor_name,json=vendorName,proto3" json:"vendor_name,omitempty"`
	VendorTaxId      string                 `protobuf:"bytes,4,opt,name=vendor_tax_id,json=vendorTaxId,proto3" json:"vendor_tax_id,omitempty"`
	VendorAddress    string                 `protobuf:"bytes,5,opt,name=vendor_address,json=vendorAddress,proto3" json:"vendor_address,omitempty"`
	Date             *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=date,proto3" json:"date,omitempty"`
	DueDate          *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=due_date,json=dueDate,proto3" json:"due_date,omitempty"`
	TotalAmount      float64                `protobuf:"fixed64,8,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	TaxAmount        float64                `protobuf:"fixed64,9,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	NetAmount        float64                `protobuf:"fixed64,10,opt,name=net_amount,json=netAmount,proto3" json:"net_amount,omitempty"`
	Currency         string                 `protobuf:"bytes,11,opt,name=currency,proto3" json:"currency,omitempty"`
	Description      string                 `protobuf:"bytes,12,opt,name=description,proto3" json:"description,omitempty"`
	Category         string                 `protobuf:"bytes,13,opt,name=category,proto3" json:"category,omitempty"`
	Status           string                 `protobuf:"bytes,14,opt,name=status,proto3" json:"status,omitempty"`
	Items            []*InvoiceItem         `protobuf:"bytes,15,rep,name=items,proto3" json:"items,omitempty"`
	ReceiptImagePath string                 `protobuf:"bytes,16,opt,name=receipt_image_path,json=receiptImagePath,proto3" json:"receipt_image_path,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (m *Invoice) Reset()         { *m = Invoice{} }
func (m *Invoice) String() string { return proto.CompactTextString(m) }
func (*Invoice) ProtoMessage()    {}
func (*Invoice) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{0}
}

// InvoiceItem represents a single invoice item
type InvoiceItem struct {
	Id          string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Quantity    float64 `protobuf:"fixed64,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice   float64 `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice  float64 `protobuf:"fixed64,6,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	TaxRate     float64 `protobuf:"fixed64,7,opt,name=tax_rate,json=taxRate,proto3" json:"tax_rate,omitempty"`
	TaxAmount   float64 `protobuf:"fixed64,8,opt,name=tax_amount,json=taxAmount,proto3" json:"tax_amount,omitempty"`
	Category    string  `protobuf:"bytes,9,opt,name=category,proto3" json:"category,omitempty"`
}

func (m *InvoiceItem) Reset()         { *m = InvoiceItem{} }
func (m *InvoiceItem) String() string { return proto.CompactTextString(m) }
func (*InvoiceItem) ProtoMessage()    {}
func (*InvoiceItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{1}
}

// Dashboard statistics
type DashboardStats struct {
	TotalRevenue     float64            `protobuf:"fixed64,1,opt,name=total_revenue,json=totalRevenue,proto3" json:"total_revenue,omitempty"`
	TotalExpenses    float64            `protobuf:"fixed64,2,opt,name=total_expenses,json=totalExpenses,proto3" json:"total_expenses,omitempty"`
	NetProfit        float64            `protobuf:"fixed64,3,opt,name=net_profit,json=netProfit,proto3" json:"net_profit,omitempty"`
	TotalInvoices    int32              `protobuf:"varint,4,opt,name=total_invoices,json=totalInvoices,proto3" json:"total_invoices,omitempty"`
	PendingInvoices  int32              `protobuf:"varint,5,opt,name=pending_invoices,json=pendingInvoices,proto3" json:"pending_invoices,omitempty"`
	OverdueInvoices  int32              `protobuf:"varint,6,opt,name=overdue_invoices,json=overdueInvoices,proto3" json:"overdue_invoices,omitempty"`
	MonthlyRevenue   float64            `protobuf:"fixed64,7,opt,name=monthly_revenue,json=monthlyRevenue,proto3" json:"monthly_revenue,omitempty"`
	MonthlyExpenses  float64            `protobuf:"fixed64,8,opt,name=monthly_expenses,json=monthlyExpenses,proto3" json:"monthly_expenses,omitempty"`
	MonthlyData      []*MonthlyData     `protobuf:"bytes,9,rep,name=monthly_data,json=monthlyData,proto3" json:"monthly_data,omitempty"`
	CategoryExpenses []*CategoryExpense `protobuf:"bytes,10,rep,name=category_expenses,json=categoryExpenses,proto3" json:"category_expenses,omitempty"`
}

func (m *DashboardStats) Reset()         { *m = DashboardStats{} }
func (m *DashboardStats) String() string { return proto.CompactTextString(m) }
func (*DashboardStats) ProtoMessage()    {}
func (*DashboardStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{2}
}

type MonthlyData struct {
	Month    string  `protobuf:"bytes,1,opt,name=month,proto3" json:"month,omitempty"`
	Revenue  float64 `protobuf:"fixed64,2,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Expenses float64 `protobuf:"fixed64,3,opt,name=expenses,proto3" json:"expenses,omitempty"`
	Profit   float64 `protobuf:"fixed64,4,opt,name=profit,proto3" json:"profit,omitempty"`
}

func (m *MonthlyData) Reset()         { *m = MonthlyData{} }
func (m *MonthlyData) String() string { return proto.CompactTextString(m) }
func (*MonthlyData) ProtoMessage()    {}
func (*MonthlyData) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{3}
}

type CategoryExpense struct {
	Category   string  `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Amount     float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Percentage float64 `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
}

func (m *CategoryExpense) Reset()         { *m = CategoryExpense{} }
func (m *CategoryExpense) String() string { return proto.CompactTextString(m) }
func (*CategoryExpense) ProtoMessage()    {}
func (*CategoryExpense) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{4}
}

// ListInvoicesRequest represents a request to list invoices
type ListInvoicesRequest struct {
	Page      int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Status    string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Category  string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	StartDate *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
}

func (m *ListInvoicesRequest) Reset()         { *m = ListInvoicesRequest{} }
func (m *ListInvoicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListInvoicesRequest) ProtoMessage()    {}
func (*ListInvoicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_accounting, []int{5}
}

func init() {
	proto.RegisterType((*Invoice)(nil), "chainrice.chainrice.v1.Invoice")
	proto.RegisterType((*InvoiceItem)(nil), "chainrice.chainrice.v1.InvoiceItem")
	proto.RegisterType((*DashboardStats)(nil), "chainrice.chainrice.v1.DashboardStats")
	proto.RegisterType((*MonthlyData)(nil), "chainrice.chainrice.v1.MonthlyData")
	proto.RegisterType((*CategoryExpense)(nil), "chainrice.chainrice.v1.CategoryExpense")
	proto.RegisterType((*ListInvoicesRequest)(nil), "chainrice.chainrice.v1.ListInvoicesRequest")
}

var fileDescriptor_accounting = []byte{
	// Placeholder file descriptor
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x49, 0xce, 0x48, 0xcc,
	0xcc, 0x2b, 0xca, 0x4c, 0x4e, 0xd5, 0x47, 0xb0, 0xca, 0x0c, 0xf5, 0x4a, 0x73, 0x93, 0x33, 0x93,
	0x33, 0x12, 0x33, 0xf3, 0x92, 0x53, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0xc4, 0xe0, 0x72,
	0x7a, 0x08, 0x56, 0x99, 0xa1, 0x94, 0x60, 0x62, 0x6e, 0x66, 0x5e, 0xbe, 0x3e, 0x98, 0x84, 0x28,
	0x95, 0x12, 0x49, 0xcf, 0x4f, 0xcf, 0x07, 0x33, 0xf5, 0x41, 0x2c, 0xa8, 0xa8, 0x32, 0x0e, 0x6b,
	0x0a, 0x12, 0x8b, 0x12, 0x73, 0xa1, 0xb6, 0x28, 0x05, 0x72, 0xf1, 0xb8, 0x43, 0xac, 0x0d, 0x2e,
	0x49, 0x2c, 0x49, 0x15, 0x72, 0xe4, 0x62, 0x83, 0xc8, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b,
	0xc9, 0xe9, 0x61, 0x77, 0x86, 0x5e, 0x00, 0x58, 0x95, 0x13, 0xe7, 0x89, 0x7b, 0xf2, 0x0c, 0x2b,
	0x9e, 0x6f, 0xd0, 0x62, 0x0c, 0x82, 0x6a, 0x74, 0x32, 0x3b, 0xf1, 0x48, 0x8e, 0xf1, 0xc2, 0x23,
	0x39, 0xc6, 0x07, 0x8f, 0xe4, 0x18, 0x27, 0x3c, 0x96, 0x63, 0xb8, 0xf0, 0x58, 0x8e, 0xe1, 0xc6,
	0x63, 0x39, 0x86, 0x28, 0x19, 0xb0, 0x09, 0xba, 0x60, 0x87, 0x54, 0x20, 0x39, 0xaa, 0xa4, 0xb2,
	0x20, 0xb5, 0x38, 0x89, 0x0d, 0xec, 0x22, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x50,
	0xe2, 0x9e, 0x1f, 0x01, 0x00, 0x00,
}

// Simple implementations of the required methods
func (m *Invoice) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *Invoice) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *Invoice) Size() int {
	return proto.Size(m)
}

func (m *InvoiceItem) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *InvoiceItem) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *InvoiceItem) Size() int {
	return proto.Size(m)
}

func (m *DashboardStats) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *DashboardStats) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *DashboardStats) Size() int {
	return proto.Size(m)
}

func (m *MonthlyData) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *MonthlyData) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *MonthlyData) Size() int {
	return proto.Size(m)
}

func (m *CategoryExpense) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *CategoryExpense) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *CategoryExpense) Size() int {
	return proto.Size(m)
}

func (m *ListInvoicesRequest) Marshal() ([]byte, error) {
	return proto.Marshal(m)
}

func (m *ListInvoicesRequest) Unmarshal(data []byte) error {
	return proto.Unmarshal(data, m)
}

func (m *ListInvoicesRequest) Size() int {
	return proto.Size(m)
}
