version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: examples-docker-hello:latest
    environment:
      - APP_NAME=examples-docker-hello-compose
      - PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped


