#!/usr/bin/env zsh
# =============================================================================
# Chain Rice Zsh Configuration Script
# =============================================================================
# This script provides comprehensive Zsh configuration for the Chain Rice
# development environment, including themes, plugins, and productivity features.
#
# Usage: source config.zsh
# Or add to your .zshrc: source /path/to/config.zsh
# =============================================================================

# =============================================================================
# Configuration Variables
# =============================================================================

# Colors
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly PURPLE='\033[0;35m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'

# Project paths
readonly CHAIN_RICE_ROOT="/media/mrdinkelman/Dev/chain-rice"
readonly CHAIN_RICE_SCRIPTS="$CHAIN_RICE_ROOT/examples/scripts"

# Plugin directories
readonly ZSH_PLUGINS_DIR="$HOME/.zsh-plugins"
readonly ZSH_THEMES_DIR="$HOME/.zsh-themes"

# =============================================================================
# Utility Functions
# =============================================================================

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_debug() {
    [[ "$DEBUG" == "true" ]] && echo -e "${BLUE}[DEBUG]${NC} $1"
}

# =============================================================================
# Directory Creation and Setup
# =============================================================================

setup_directories() {
    local dirs=("$ZSH_PLUGINS_DIR" "$ZSH_THEMES_DIR" "$HOME/.zsh-cache")
    
    for dir in "${dirs[@]}"; do
        if [[ ! -d "$dir" ]]; then
            mkdir -p "$dir"
            log_debug "Created directory: $dir"
        fi
    done
}

# =============================================================================
# Plugin Management
# =============================================================================

install_plugin() {
    local plugin_name="$1"
    local plugin_url="$2"
    local plugin_dir="$ZSH_PLUGINS_DIR/$plugin_name"
    
    if [[ ! -d "$plugin_dir" ]]; then
        log_info "Installing plugin: $plugin_name"
        git clone "$plugin_url" "$plugin_dir"
    else
        log_debug "Plugin $plugin_name already installed"
    fi
}

load_plugin() {
    local plugin_name="$1"
    local plugin_file="$2"
    local plugin_dir="$ZSH_PLUGINS_DIR/$plugin_name"
    
    if [[ -f "$plugin_dir/$plugin_file" ]]; then
        source "$plugin_dir/$plugin_file"
        log_debug "Loaded plugin: $plugin_name"
    else
        log_warn "Plugin file not found: $plugin_dir/$plugin_file"
    fi
}

# =============================================================================
# Essential Plugins Installation
# =============================================================================

install_essential_plugins() {
    log_info "Installing essential Zsh plugins..."
    
    # Oh My Zsh (if not already installed)
    if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
        log_info "Installing Oh My Zsh..."
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
    fi
    
    # Zsh Autosuggestions
    install_plugin "zsh-autosuggestions" "https://github.com/zsh-users/zsh-autosuggestions.git"
    
    # Zsh Syntax Highlighting
    install_plugin "zsh-syntax-highlighting" "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    
    # Zsh Completions
    install_plugin "zsh-completions" "https://github.com/zsh-users/zsh-completions.git"
    
    # Powerlevel10k Theme
    install_plugin "powerlevel10k" "https://github.com/romkatv/powerlevel10k.git"
    
    # FZF
    if ! command -v fzf >/dev/null 2>&1; then
        log_info "Installing FZF..."
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
        ~/.fzf/install --key-bindings --completion --no-update-rc
    fi
    
    log_info "Essential plugins installed successfully"
}

# =============================================================================
# Theme Configuration
# =============================================================================

setup_powerlevel10k() {
    log_info "Setting up Powerlevel10k theme..."
    
    # Create Powerlevel10k configuration
    cat > "$HOME/.p10k.zsh" << 'EOF'
# Generated by Chain Rice config.zsh
# Powerlevel10k configuration

# Enable Powerlevel10k instant prompt
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Powerlevel10k theme
source ~/.zsh-plugins/powerlevel10k/powerlevel10k.zsh-theme

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Prompt elements
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir
  vcs
  newline
  prompt_char
)

POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  virtualenv
  anaconda
  pyenv
  nodenv
  nvm
  nodeenv
  node_version
  go_version
  rust_version
  java_version
  scala_version
  time
)

# Directory settings
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_last
POWERLEVEL9K_SHORTEN_DELIMITER=
POWERLEVEL9K_DIR_FOREGROUND=39
POWERLEVEL9K_DIR_BACKGROUND=236

# VCS settings
POWERLEVEL9K_VCS_CLEAN_FOREGROUND=76
POWERLEVEL9K_VCS_CLEAN_BACKGROUND=236
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=76
POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=236
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=196
POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=236

# Status settings
POWERLEVEL9K_STATUS_OK_FOREGROUND=70
POWERLEVEL9K_STATUS_OK_BACKGROUND=236
POWERLEVEL9K_STATUS_ERROR_FOREGROUND=160
POWERLEVEL9K_STATUS_ERROR_BACKGROUND=236

# Time settings
POWERLEVEL9K_TIME_FOREGROUND=66
POWERLEVEL9K_TIME_BACKGROUND=236
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'

# Version settings
POWERLEVEL9K_NODE_VERSION_FOREGROUND=70
POWERLEVEL9K_NODE_VERSION_BACKGROUND=236
POWERLEVEL9K_GO_VERSION_FOREGROUND=70
POWERLEVEL9K_GO_VERSION_BACKGROUND=236
POWERLEVEL9K_RUST_VERSION_FOREGROUND=70
POWERLEVEL9K_RUST_VERSION_BACKGROUND=236
POWERLEVEL9K_JAVA_VERSION_FOREGROUND=70
POWERLEVEL9K_JAVA_VERSION_BACKGROUND=236
POWERLEVEL9K_SCALA_VERSION_FOREGROUND=70
POWERLEVEL9K_SCALA_VERSION_BACKGROUND=236
EOF
    
    log_info "Powerlevel10k theme configured"
}

# =============================================================================
# Aliases and Functions
# =============================================================================

setup_aliases() {
    log_info "Setting up aliases and functions..."
    
    # Chain Rice specific aliases
    alias cr='cd $CHAIN_RICE_ROOT'
    alias cr-build='cd $CHAIN_RICE_ROOT && make build'
    alias cr-test='cd $CHAIN_RICE_ROOT && make test'
    alias cr-run='cd $CHAIN_RICE_ROOT && make run'
    alias cr-docker='cd $CHAIN_RICE_ROOT && docker-compose up -d'
    alias cr-logs='cd $CHAIN_RICE_ROOT && docker-compose logs -f'
    alias cr-clean='cd $CHAIN_RICE_ROOT && make clean'
    alias cr-start='$CHAIN_RICE_SCRIPTS/start.sh'
    alias cr-stop='$CHAIN_RICE_SCRIPTS/start.sh stop'
    alias cr-status='$CHAIN_RICE_SCRIPTS/start.sh status'
    alias cr-restart='$CHAIN_RICE_SCRIPTS/start.sh restart'
    
    # General development aliases
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
    
    # Git aliases
    alias gs='git status'
    alias ga='git add'
    alias gc='git commit'
    alias gp='git push'
    alias gl='git log --oneline'
    alias gd='git diff'
    alias gb='git branch'
    alias gco='git checkout'
    alias gcb='git checkout -b'
    alias gm='git merge'
    alias gr='git rebase'
    alias gf='git fetch'
    alias gpull='git pull'
    alias gstash='git stash'
    alias gpop='git stash pop'
    
    # Docker aliases
    alias d='docker'
    alias dc='docker-compose'
    alias dps='docker ps'
    alias dpa='docker ps -a'
    alias di='docker images'
    alias drm='docker rm'
    alias drmi='docker rmi'
    alias dlog='docker logs'
    alias dexec='docker exec -it'
    
    # System aliases
    alias ..='cd ..'
    alias ...='cd ../..'
    alias ....='cd ../../..'
    alias .....='cd ../../../..'
    alias ~='cd ~'
    alias -- -='cd -'
    
    # Network aliases
    alias ports='netstat -tuln'
    alias myip='curl -s https://ipinfo.io/ip'
    alias localip='ip route get 1 | awk "{print \$7}"'
    
    # Process aliases
    alias psg='ps aux | grep'
    alias killg='killall -9'
    
    log_info "Aliases configured successfully"
}

setup_functions() {
    log_info "Setting up custom functions..."
    
    # Function to quickly navigate to Chain Rice project
    cr() {
        cd "$CHAIN_RICE_ROOT"
    }
    
    # Function to run project tests
    cr-test() {
        cd "$CHAIN_RICE_ROOT"
        make test
    }
    
    # Function to build project
    cr-build() {
        cd "$CHAIN_RICE_ROOT"
        make build
    }
    
    # Function to start services
    cr-start() {
        "$CHAIN_RICE_SCRIPTS/start.sh" start "$@"
    }
    
    # Function to stop services
    cr-stop() {
        "$CHAIN_RICE_SCRIPTS/start.sh" stop "$@"
    }
    
    # Function to show service status
    cr-status() {
        "$CHAIN_RICE_SCRIPTS/start.sh" status
    }
    
    # Function to show logs
    cr-logs() {
        "$CHAIN_RICE_SCRIPTS/start.sh" logs "$@"
    }
    
    # Function to create a new git branch
    gcb() {
        local branch_name="$1"
        if [[ -z "$branch_name" ]]; then
            echo "Usage: gcb <branch-name>"
            return 1
        fi
        git checkout -b "$branch_name"
    }
    
    # Function to find files
    ff() {
        local pattern="$1"
        if [[ -z "$pattern" ]]; then
            echo "Usage: ff <pattern>"
            return 1
        fi
        find . -type f -name "*$pattern*" 2>/dev/null
    }
    
    # Function to find directories
    fd() {
        local pattern="$1"
        if [[ -z "$pattern" ]]; then
            echo "Usage: fd <pattern>"
            return 1
        fi
        find . -type d -name "*$pattern*" 2>/dev/null
    }
    
    # Function to search in files
    sg() {
        local pattern="$1"
        local path="${2:-.}"
        if [[ -z "$pattern" ]]; then
            echo "Usage: sg <pattern> [path]"
            return 1
        fi
        grep -r "$pattern" "$path" 2>/dev/null
    }
    
    # Function to extract archives
    extract() {
        if [[ -f "$1" ]]; then
            case "$1" in
                *.tar.bz2)   tar xjf "$1"     ;;
                *.tar.gz)    tar xzf "$1"     ;;
                *.bz2)       bunzip2 "$1"      ;;
                *.rar)       unrar e "$1"      ;;
                *.gz)        gunzip "$1"       ;;
                *.tar)       tar xf "$1"       ;;
                *.tbz2)      tar xjf "$1"      ;;
                *.tgz)       tar xzf "$1"      ;;
                *.zip)       unzip "$1"        ;;
                *.Z)         uncompress "$1"   ;;
                *.7z)        7z x "$1"         ;;
                *)           echo "'$1' cannot be extracted via extract()" ;;
            esac
        else
            echo "'$1' is not a valid file"
        fi
    }
    
    # Function to create directory and cd into it
    mkcd() {
        local dir="$1"
        if [[ -z "$dir" ]]; then
            echo "Usage: mkcd <directory>"
            return 1
        fi
        mkdir -p "$dir" && cd "$dir"
    }
    
    # Function to show weather
    weather() {
        local city="${1:-}"
        if [[ -n "$city" ]]; then
            curl -s "wttr.in/$city"
        else
            curl -s "wttr.in"
        fi
    }
    
    # Function to show system info
    sysinfo() {
        echo "=== System Information ==="
        echo "OS: $(uname -s)"
        echo "Kernel: $(uname -r)"
        echo "Architecture: $(uname -m)"
        echo "Hostname: $(hostname)"
        echo "Uptime: $(uptime)"
        echo "Memory: $(free -h | grep '^Mem:' | awk '{print $3 "/" $2}')"
        echo "Disk: $(df -h / | tail -1 | awk '{print $3 "/" $2 " (" $5 " used)"}')"
        echo "CPU: $(lscpu | grep 'Model name' | cut -d: -f2 | xargs)"
    }
    
    log_info "Custom functions configured successfully"
}

# =============================================================================
# Completion System
# =============================================================================

setup_completions() {
    log_info "Setting up completion system..."
    
    # Enable completion system
    autoload -Uz compinit
    compinit
    
    # Case insensitive completion
    zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
    
    # Menu selection
    zstyle ':completion:*' menu select
    
    # Group matches
    zstyle ':completion:*' group-name ''
    zstyle ':completion:*:descriptions' format '%B%d%b'
    
    # Cache completions
    zstyle ':completion:*' use-cache on
    zstyle ':completion:*' cache-path ~/.zsh-cache
    
    # Fuzzy matching
    zstyle ':completion:*' completer _complete _match _approximate
    zstyle ':completion:*:match:*' original only
    zstyle ':completion:*:approximate:*' max-errors 1 numeric
    
    # Colors for completions
    zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
    
    # Chain Rice specific completions
    _cr_completion() {
        local -a commands
        commands=(
            'start:Start services'
            'stop:Stop services'
            'restart:Restart services'
            'status:Show service status'
            'logs:Show service logs'
            'build:Build all components'
            'test:Run tests'
            'clean:Clean build artifacts'
            'backup:Create backup'
            'restore:Restore backup'
            'deploy:Deploy to production'
        )
        _describe 'cr commands' commands
    }
    
    compdef _cr_completion cr-start cr-stop cr-restart cr-status cr-logs
    
    log_info "Completion system configured successfully"
}

# =============================================================================
# Key Bindings
# =============================================================================

setup_key_bindings() {
    log_info "Setting up key bindings..."
    
    # Use emacs key bindings
    bindkey -e
    
    # History search
    bindkey '^R' history-incremental-search-backward
    bindkey '^S' history-incremental-search-forward
    
    # Word navigation
    bindkey '^[[1;5C' forward-word
    bindkey '^[[1;5D' backward-word
    
    # Beginning and end of line
    bindkey '^A' beginning-of-line
    bindkey '^E' end-of-line
    
    # Delete word
    bindkey '^W' backward-kill-word
    
    # FZF key bindings (if available)
    if command -v fzf >/dev/null 2>&1; then
        source ~/.fzf.zsh
    fi
    
    log_info "Key bindings configured successfully"
}

# =============================================================================
# History Configuration
# =============================================================================

setup_history() {
    log_info "Setting up history configuration..."
    
    # History file
    HISTFILE="$HOME/.zsh_history"
    
    # History size
    HISTSIZE=10000
    SAVEHIST=10000
    
    # History options
    setopt HIST_VERIFY
    setopt SHARE_HISTORY
    setopt APPEND_HISTORY
    setopt INC_APPEND_HISTORY
    setopt HIST_IGNORE_DUPS
    setopt HIST_IGNORE_ALL_DUPS
    setopt HIST_REDUCE_BLANKS
    setopt HIST_IGNORE_SPACE
    setopt HIST_SAVE_NO_DUPS
    setopt HIST_EXPIRE_DUPS_FIRST
    setopt HIST_FIND_NO_DUPS
    
    log_info "History configuration completed"
}

# =============================================================================
# Environment Variables
# =============================================================================

setup_environment() {
    log_info "Setting up environment variables..."
    
    # Editor
    export EDITOR='vim'
    export VISUAL='vim'
    
    # Pager
    export PAGER='less'
    export LESS='-R'
    
    # Language
    export LANG='en_US.UTF-8'
    export LC_ALL='en_US.UTF-8'
    
    # Path
    export PATH="$HOME/.local/bin:$PATH"
    export PATH="$HOME/.cargo/bin:$PATH"
    export PATH="$HOME/.go/bin:$PATH"
    export PATH="/usr/local/go/bin:$PATH"
    
    # Chain Rice specific
    export CHAIN_RICE_ROOT="$CHAIN_RICE_ROOT"
    export CHAIN_RICE_SCRIPTS="$CHAIN_RICE_SCRIPTS"
    
    # Development tools
    export RUST_BACKTRACE=1
    export CARGO_TARGET_DIR="$CHAIN_RICE_ROOT/target"
    
    # Node.js
    export NODE_ENV=development
    
    # Python
    export PYTHONPATH="$CHAIN_RICE_ROOT:$PYTHONPATH"
    
    # Go
    export GOPATH="$HOME/go"
    export GOBIN="$GOPATH/bin"
    export PATH="$GOBIN:$PATH"
    
    # Java
    export JAVA_HOME="/usr/lib/jvm/java-17-openjdk"
    export PATH="$JAVA_HOME/bin:$PATH"
    
    # Scala
    export SCALA_HOME="/usr/local/scala"
    export PATH="$SCALA_HOME/bin:$PATH"
    
    log_info "Environment variables configured successfully"
}

# =============================================================================
# Plugin Loading
# =============================================================================

load_plugins() {
    log_info "Loading Zsh plugins..."
    
    # Load Oh My Zsh
    if [[ -d "$HOME/.oh-my-zsh" ]]; then
        export ZSH="$HOME/.oh-my-zsh"
        source "$ZSH/oh-my-zsh.sh"
    fi
    
    # Load custom plugins
    load_plugin "zsh-autosuggestions" "zsh-autosuggestions.zsh"
    load_plugin "zsh-syntax-highlighting" "zsh-syntax-highlighting.zsh"
    load_plugin "zsh-completions" "zsh-completions.plugin.zsh"
    
    # Load Powerlevel10k
    if [[ -f "$HOME/.p10k.zsh" ]]; then
        source "$HOME/.p10k.zsh"
    fi
    
    log_info "Plugins loaded successfully"
}

# =============================================================================
# Main Configuration Function
# =============================================================================

configure_zsh() {
    log_info "Starting Zsh configuration for Chain Rice..."
    
    # Setup directories
    setup_directories
    
    # Install plugins if needed
    if [[ "$INSTALL_PLUGINS" == "true" ]]; then
        install_essential_plugins
        setup_powerlevel10k
    fi
    
    # Configure Zsh
    setup_aliases
    setup_functions
    setup_completions
    setup_key_bindings
    setup_history
    setup_environment
    
    # Load plugins
    load_plugins
    
    log_info "Zsh configuration completed successfully!"
    log_info "Chain Rice development environment is ready."
    log_info "Use 'cr' to navigate to the project directory."
    log_info "Use 'cr-start', 'cr-stop', 'cr-status' for service management."
}

# =============================================================================
# Script Entry Point
# =============================================================================

# Configuration options
INSTALL_PLUGINS="${INSTALL_PLUGINS:-false}"
DEBUG="${DEBUG:-false}"

# Run configuration
configure_zsh

# Clean up
unset -f log_info log_warn log_error log_debug
unset -f setup_directories install_plugin load_plugin
unset -f install_essential_plugins setup_powerlevel10k
unset -f setup_aliases setup_functions setup_completions
unset -f setup_key_bindings setup_history setup_environment
unset -f load_plugins configure_zsh
