package terraform

// Generated from .opentofu — do not edit by hand; re-run embed script or edit .opentofu then re-embed.

environmentFiles: [string]: string
environmentFiles: {
	"environments/dev/backend.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Optional remote state — uncomment ONE backend block and set resource names from your account.
# OpenTofu/Terraform only allow a single backend stanza per configuration.
#
# --- AWS (S3 + DynamoDB lock) example ---
# terraform {
#   backend "s3" {
#     bucket         = "rice-tf-state-ACCOUNTID"
#     key            = "rice/dev/terraform.tfstate"
#     region         = "eu-west-1"
#     encrypt        = true
#     dynamodb_table = "rice-tf-locks"
#   }
# }
#
# --- GCP (GCS) example ---
# terraform {
#   backend "gcs" {
#     bucket = "rice-tf-state-PROJECT"
#     prefix = "dev"
#   }
# }
#
# --- Azure (azurerm) example ---
# terraform {
#   backend "azurerm" {
#     resource_group_name  = "rice-tf-state"
#     storage_account_name = "ricetfstate"
#     container_name         = "tfstate"
#     key                    = "dev.terraform.tfstate"
#   }
# }

terraform {
  backend "local" {
    path = ".terraform/state/rice-dev.tfstate"
  }
}
"""#
	"environments/dev/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
terraform {
  required_version = ">= 1.6.0"
}

# Full module graph: `cd ..` (repo `.opentofu`) then `tofu init && tofu apply -var-file=environments/dev/terraform.tfvars`.
resource "terraform_data" "environment_marker" {
  input = {
    name = "dev"
    note = "Root stack: parent .opentofu/main.tf + modules/*"
  }
}
"""#
	"environments/dev/terraform.tfvars": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
rice_environment         = "dev"
rice_cloud_provider      = "aws"
rice_k8s_cluster_name    = "rice-dev"
rice_db_instance_class    = "db.t4g.micro"
rice_enable_gpu          = false
rice_gpu_instance_type    = ""
rice_github_org          = "rice-rob-inn-com-ent"
rice_github_repo         = "rice"
rice_domain              = "dev.example.invalid"
rice_registry            = "ghcr.io"
rice_region              = "eu-west-1"
rice_availability_zones  = ["eu-west-1a", "eu-west-1b"]
rice_vpc_cidr            = "10.0.0.0/16"
rice_aws_region          = "eu-west-1"
rice_aws_assume_role_arn = ""
rice_gcp_project_id      = ""
rice_gcp_region          = "europe-west1"
rice_azure_subscription_id = ""
rice_azure_tenant_id     = ""
rice_kubeconfig_path     = "~/.kube/config"
rice_tf_backend          = "local"
"""#
	"environments/prod/backend.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Remote state: use S3/GCS/azurerm in production; templates in environments/dev/backend.tf.

terraform {
  backend "local" {
    path = ".terraform/state/rice-prod.tfstate"
  }
}
"""#
	"environments/prod/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
terraform {
  required_version = ">= 1.6.0"
}

resource "terraform_data" "environment_marker" {
  input = {
    name = "prod"
    note = "Root stack: parent .opentofu/main.tf + modules/*"
  }
}
"""#
	"environments/prod/terraform.tfvars": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
rice_environment         = "prod"
rice_cloud_provider      = "aws"
rice_k8s_cluster_name    = "rice-prod"
rice_db_instance_class    = "db.r6g.large"
rice_enable_gpu          = true
rice_gpu_instance_type    = "g5.xlarge"
rice_github_org          = "rice-rob-inn-com-ent"
rice_github_repo         = "rice"
rice_domain              = "example.invalid"
rice_registry            = "ghcr.io"
rice_region              = "eu-west-1"
rice_availability_zones  = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
rice_vpc_cidr            = "10.2.0.0/16"
rice_aws_region          = "eu-west-1"
rice_aws_assume_role_arn = ""
rice_gcp_project_id      = ""
rice_gcp_region          = "europe-west1"
rice_azure_subscription_id = ""
rice_azure_tenant_id     = ""
rice_kubeconfig_path     = "~/.kube/config"
rice_tf_backend          = "local"
"""#
	"environments/stag/backend.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Remote state: see dev/backend.tf in this repo for commented s3/gcs/azurerm templates.

terraform {
  backend "local" {
    path = ".terraform/state/rice-stag.tfstate"
  }
}
"""#
	"environments/stag/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
terraform {
  required_version = ">= 1.6.0"
}

resource "terraform_data" "environment_marker" {
  input = {
    name = "stag"
    note = "Root stack: parent .opentofu/main.tf + modules/*"
  }
}
"""#
	"environments/stag/terraform.tfvars": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
rice_environment         = "stag"
rice_cloud_provider      = "aws"
rice_k8s_cluster_name    = "rice-stag"
rice_db_instance_class    = "db.t4g.small"
rice_enable_gpu          = false
rice_gpu_instance_type    = ""
rice_github_org          = "rice-rob-inn-com-ent"
rice_github_repo         = "rice"
rice_domain              = "stag.example.invalid"
rice_registry            = "ghcr.io"
rice_region              = "eu-west-1"
rice_availability_zones  = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]
rice_vpc_cidr            = "10.1.0.0/16"
rice_aws_region          = "eu-west-1"
rice_aws_assume_role_arn = ""
rice_gcp_project_id      = ""
rice_gcp_region          = "europe-west1"
rice_azure_subscription_id = ""
rice_azure_tenant_id     = ""
rice_kubeconfig_path     = "~/.kube/config"
rice_tf_backend          = "local"
"""#
}
