package terraform

// Generated from .opentofu — do not edit by hand; re-run embed script or edit .opentofu then re-embed.

rootStaticFiles: [string]: string
rootStaticFiles: {
	"main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
locals {
  rice_deployments = var.rice_deployments
}

module "clusters" {
  for_each = local.rice_deployments
  source   = "./modules/clusters"

  rice_environment         = var.rice_environment
  rice_cloud_provider      = each.value.cloud
  rice_region              = each.value.region
  rice_vpc_cidr            = each.value.vpc_cidr
  rice_k8s_cluster_name    = var.rice_k8s_cluster_name
  rice_availability_zones  = var.rice_availability_zones
  rice_enable_gpu          = var.rice_enable_gpu
  rice_gpu_instance_type   = var.rice_gpu_instance_type
}

module "databases" {
  for_each = local.rice_deployments
  source   = "./modules/databases"

  rice_environment       = var.rice_environment
  rice_cloud_provider    = each.value.cloud
  rice_region            = each.value.region
  rice_db_instance_class = var.rice_db_instance_class
}

module "auth" {
  source = "./modules/auth"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_github_org     = var.rice_github_org
  rice_github_repo    = var.rice_github_repo
}

module "certificates" {
  source = "./modules/certificates"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_domain         = var.rice_domain
}

module "routes" {
  source = "./modules/routes"

  rice_environment    = var.rice_environment
  rice_cloud_provider = var.rice_cloud_provider
  rice_domain         = var.rice_domain
}

module "stores" {
  for_each = local.rice_deployments
  source   = "./modules/stores"

  rice_environment    = var.rice_environment
  rice_cloud_provider = each.value.cloud
  rice_region         = each.value.region
}

module "kubernetes" {
  for_each = local.rice_deployments
  source   = "./modules/kubernetes"

  rice_environment      = var.rice_environment
  rice_cloud_provider     = each.value.cloud
  rice_region             = each.value.region
  rice_k8s_cluster_name   = var.rice_k8s_cluster_name
}
"""#
	"outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_tf_backend" {
  value       = var.rice_tf_backend
  description = "Operator hint for state storage (local | s3 | gcs | azurerm); backend blocks live under environments/*/backend.tf."
}

output "rice_environment" {
  value       = var.rice_environment
  description = "Active environment label."
}

output "rice_cloud_provider" {
  value       = var.rice_cloud_provider
  description = "Primary cloud selection."
}

output "rice_k8s_endpoint" {
  value       = format("https://api.%s.$${var.rice_region}.$${var.rice_cloud_provider}.rice-stub.invalid:6443", replace(var.rice_k8s_cluster_name, "/", "-"))
  description = "Synthetic API hostname until the clusters module exports a real control plane URL."
}

output "rice_registry_url" {
  value       = "$${var.rice_registry}/$${var.rice_github_org}/$${var.rice_github_repo}"
  description = "Default OCI image prefix for CI pushes."
}

output "rice_db_connection_string" {
  value       = length(module.databases) > 0 ? format("postgresql://rice:CHANGEME@%s-%s-pg.rice-stub.invalid:5432/rice_$${var.rice_environment}?sslmode=require", values(module.databases)[0].probe.cloud_provider, values(module.databases)[0].probe.region) : ""
  sensitive   = true
  description = "Placeholder JDBC-style URL from databases probe; replace when RDS/Cloud SQL/... exists."
}

output "rice_kms_key_id" {
  value       = format("alias/rice-%s-%s-kms-stub", var.rice_environment, var.rice_cloud_provider)
  description = "KMS alias placeholder; wire to module.auth when cloud KMS keys are created."
}

output "rice_nats_lb_ip" {
  value       = format("nat-lb-%s-%s-pending", var.rice_environment, var.rice_region)
  description = "Placeholder until routes/stores modules publish a messaging load balancer hostname or IP."
}

output "rice_harbor_hostname" {
  value       = "harbor.$${var.rice_domain}"
  description = "Default Harbor hostname pattern (adjust when Harbor module exists)."
}

output "module_probes" {
  value = {
    clusters     = { for k, m in module.clusters : k => m.probe }
    databases    = { for k, m in module.databases : k => m.probe }
    auth         = module.auth.probe
    certificates = module.certificates.probe
    routes       = module.routes.probe
    stores       = { for k, m in module.stores : k => m.probe }
    kubernetes   = { for k, m in module.kubernetes : k => m.probe }
  }
  description = "Stub probes from each module — replace with real outputs as implementations land."
}
"""#
	"providers.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# Root-level provider aliases — detailed blocks also live under `providers/{aws,gcp,azure}/`.
# Kubernetes / Helm / kubectl / sops providers are declared in required_providers; configure them when modules need cluster access.

locals {
  kubeconfig = pathexpand(var.rice_kubeconfig_path)
}

provider "kubernetes" {
  config_path = local.kubeconfig
}

provider "helm" {
  kubernetes {
    config_path = local.kubeconfig
  }
}

provider "kubectl" {
  config_path = local.kubeconfig
}

locals {
  enable_aws   = contains(var.rice_enabled_clouds, "aws")
  enable_gcp   = contains(var.rice_enabled_clouds, "gcp")
  enable_azure = contains(var.rice_enabled_clouds, "azure")
}

provider "aws" {
  region = var.rice_aws_region

  dynamic "assume_role" {
    for_each = var.rice_aws_assume_role_arn != "" ? [1] : []
    content {
      role_arn = var.rice_aws_assume_role_arn
    }
  }
}

provider "google" {
  project               = var.rice_gcp_project_id
  region                = var.rice_gcp_region
  user_project_override = true
}

provider "azurerm" {
  features {}

  subscription_id = var.rice_azure_subscription_id != "" ? var.rice_azure_subscription_id : null
  tenant_id       = var.rice_azure_tenant_id != "" ? var.rice_azure_tenant_id : null
}
"""#
	"variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" {
  type        = string
  description = "Deployment slice: dev | stag | prod."
  validation {
    condition     = contains(["dev", "stag", "prod"], var.rice_environment)
    error_message = "rice_environment must be dev, stag, or prod."
  }
}

variable "rice_cloud_provider" {
  type        = string
  description = "Primary cloud: aws | gcp | azure | all (multi-cloud planning)."
  validation {
    condition     = contains(["aws", "gcp", "azure", "all"], var.rice_cloud_provider)
    error_message = "rice_cloud_provider must be aws, gcp, azure, or all."
  }
}

variable "rice_github_org" {
  type        = string
  description = "GitHub org for CI / OIDC (required for auth module wiring)."
}

variable "rice_github_repo" {
  type        = string
  description = "GitHub repository name under rice_github_org."
}

variable "rice_domain" {
  type        = string
  description = "Public DNS apex for ingress / ACM / managed certs."
}

variable "rice_k8s_cluster_name" {
  type        = string
  description = "Logical Kubernetes cluster name (tags / resource names)."
}

variable "rice_db_instance_class" {
  type        = string
  description = "Default DB instance / tier class per provider."
}

variable "rice_registry" {
  type        = string
  description = "OCI registry host for images (default GHCR)."
  default     = "ghcr.io"
}

variable "rice_region" {
  type        = string
  description = "Primary region slug for the active cloud (see also cloud-specific vars)."
}

variable "rice_availability_zones" {
  type        = list(string)
  description = "AZs for HA subnets / node groups."
}

variable "rice_vpc_cidr" {
  type        = string
  description = "IPv4 CIDR for workload VPC / equivalent."
  default     = "10.0.0.0/16"
}

variable "rice_enable_gpu" {
  type        = bool
  description = "Whether GPU node pools / instance types are enabled."
  default     = false
}

variable "rice_gpu_instance_type" {
  type        = string
  description = "GPU-capable instance type when rice_enable_gpu is true."
  default     = ""
}

variable "rice_aws_region" {
  type        = string
  description = "AWS region for provider + regional resources."
}

variable "rice_aws_assume_role_arn" {
  type        = string
  description = "Optional IAM role for provider assume_role."
  default     = ""
}

variable "rice_gcp_project_id" {
  type        = string
  description = "GCP project ID (replace placeholder before applying GCP resources)."
}

variable "rice_gcp_region" {
  type        = string
  description = "Default GCP region."
}

variable "rice_azure_subscription_id" {
  type        = string
  description = "Azure subscription ID (optional with az login / OIDC)."
  default     = ""
}

variable "rice_azure_tenant_id" {
  type        = string
  description = "Azure AD tenant ID (optional in many flows)."
  default     = ""
}

variable "rice_tf_backend" {
  type        = string
  description = "Hint for operators: local | s3 | gcs | azurerm (backend blocks live under environments/*/backend.tf)."
  default     = "local"
}

variable "rice_kubeconfig_path" {
  type        = string
  description = "Kubeconfig path for kubernetes / helm / kubectl providers (use an absolute path in CI)."
  default     = "~/.kube/config"
}

variable "rice_enabled_clouds" {
  type        = list(string)
  description = "Clouds active in this stack (aws, gcp, azure)."
  default     = ["aws"]
}

variable "rice_primary_cloud" {
  type        = string
  description = "Primary cloud for singleton modules and default routing."
  default     = "aws"
}

variable "rice_regions" {
  type = object({
    aws   = optional(list(string), [])
    gcp   = optional(list(string), [])
    azure = optional(list(string), [])
  })
  description = "Region lists per cloud (CHIEF regions set block)."
  default = {
    aws   = []
    gcp   = []
    azure = []
  }
}

variable "rice_regions_aws" {
  type        = list(string)
  description = "AWS regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_regions_gcp" {
  type        = list(string)
  description = "GCP regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_regions_azure" {
  type        = list(string)
  description = "Azure regions from CHIEF terraform.rice."
  default     = []
}

variable "rice_deployments" {
  type = map(object({
    cloud    = string
    region   = string
    vpc_cidr = string
  }))
  description = "Multi-cloud × multi-region deployment matrix (keys: cloud:region)."
}
"""#
	"versions.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.82"
    }
    google = {
      source  = "hashicorp/google"
      version = "~> 6.12"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 2.17"
    }
    kubectl = {
      source  = "alekc/kubectl"
      version = "~> 2.1"
    }
    sops = {
      source  = "carlpett/sops"
      version = "~> 1.0"
    }
  }
}
"""#
}
