package terraform

// Generated from .opentofu — do not edit by hand; re-run embed script or edit .opentofu then re-embed.

moduleFiles: [string]: string
moduleFiles: {
	"modules/auth/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "auth_probe" {
  input = {
    module         = "auth"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    github_org     = var.rice_github_org
    github_repo    = var.rice_github_repo
  }
}
"""#
	"modules/auth/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.auth_probe.output
}
"""#
	"modules/auth/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_github_org" { type = string }
variable "rice_github_repo" { type = string }
"""#
	"modules/certificates/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "certificates_probe" {
  input = {
    module         = "certificates"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    domain         = var.rice_domain
  }
}
"""#
	"modules/certificates/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.certificates_probe.output
}
"""#
	"modules/certificates/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_domain" { type = string }
"""#
	"modules/clusters/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
# EKS / GKE / AKS — extend with real resources; probe validates wiring from root.
resource "terraform_data" "clusters_probe" {
  input = {
    module          = "clusters"
    deployment_key  = format("%s:%s", var.rice_cloud_provider, var.rice_region)
    environment     = var.rice_environment
    cloud_provider  = var.rice_cloud_provider
    region          = var.rice_region
    vpc_cidr        = var.rice_vpc_cidr
    k8s_name        = var.rice_k8s_cluster_name
    azs             = var.rice_availability_zones
    enable_gpu      = var.rice_enable_gpu
    gpu_type        = var.rice_gpu_instance_type
  }
}
"""#
	"modules/clusters/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.clusters_probe.output
}
"""#
	"modules/clusters/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_region" { type = string }
variable "rice_vpc_cidr" { type = string }
variable "rice_k8s_cluster_name" { type = string }
variable "rice_availability_zones" { type = list(string) }
variable "rice_enable_gpu" { type = bool }
variable "rice_gpu_instance_type" { type = string }
"""#
	"modules/databases/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "databases_probe" {
  input = {
    module         = "databases"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    region         = var.rice_region
    db_class       = var.rice_db_instance_class
  }
}
"""#
	"modules/databases/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.databases_probe.output
}
"""#
	"modules/databases/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_region" { type = string }
variable "rice_db_instance_class" { type = string }
"""#
	"modules/kubernetes/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "kubernetes_probe" {
  input = {
    module         = "kubernetes"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    region         = var.rice_region
    k8s_name       = var.rice_k8s_cluster_name
  }
}
"""#
	"modules/kubernetes/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.kubernetes_probe.output
}
"""#
	"modules/kubernetes/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_region" { type = string }
variable "rice_k8s_cluster_name" { type = string }
"""#
	"modules/routes/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "routes_probe" {
  input = {
    module         = "routes"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    domain         = var.rice_domain
  }
}
"""#
	"modules/routes/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.routes_probe.output
}
"""#
	"modules/routes/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_domain" { type = string }
"""#
	"modules/stores/main.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
resource "terraform_data" "stores_probe" {
  input = {
    module         = "stores"
    environment    = var.rice_environment
    cloud_provider = var.rice_cloud_provider
    region         = var.rice_region
  }
}
"""#
	"modules/stores/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "probe" {
  value = terraform_data.stores_probe.output
}
"""#
	"modules/stores/variables.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
variable "rice_environment" { type = string }
variable "rice_cloud_provider" { type = string }
variable "rice_region" { type = string }
"""#
}
