package terraform

// Generated from .opentofu — do not edit by hand; re-run embed script or edit .opentofu then re-embed.

providerFiles: [string]: string
providerFiles: {
	"providers/aws/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_aws_region_effective" {
  value       = var.rice_aws_region
  description = "Region wired into the AWS provider."
}
"""#
	"providers/aws/provider.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "aws" {
  region = var.rice_aws_region

  dynamic "assume_role" {
    for_each = var.rice_aws_assume_role_arn != "" ? [1] : []
    content {
      role_arn = var.rice_aws_assume_role_arn
    }
  }

  default_tags {
    tags = {
      Project     = "rice"
      Environment = var.rice_environment
      ManagedBy   = "opentofu"
    }
  }
}
"""#
	"providers/aws/variables.tf": #"""
# KING TODO map
# TODO:
# [ ] fill from infra/configs/opentofu.cue — no hardcoded IDs; use var.rice_* only
"""#
	"providers/azure/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_azure_subscription_effective" {
  value       = var.rice_azure_subscription_id
  sensitive   = true
  description = "Subscription ID passed into azurerm (may be empty when using CLI / OIDC)."
}
"""#
	"providers/azure/provider.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "azurerm" {
  features {}

  subscription_id = var.rice_azure_subscription_id != "" ? var.rice_azure_subscription_id : null
  tenant_id         = var.rice_azure_tenant_id != "" ? var.rice_azure_tenant_id : null
}
"""#
	"providers/azure/variables.tf": #"""
# KING TODO map
# TODO:
# [ ] fill from infra/configs/opentofu.cue — no hardcoded IDs; use var.rice_* only
"""#
	"providers/gcp/outputs.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
output "rice_gcp_project_effective" {
  value       = var.rice_gcp_project_id
  description = "GCP project ID wired into the google provider."
}
"""#
	"providers/gcp/provider.tf": #"""
# Code generated by MASON — cue cmd gen ./infra/terraform DO NOT EDIT.
# Source: infra/terraform/cue/*.cue — edit CUE and re-run gen.
provider "google" {
  project                 = var.rice_gcp_project_id
  region                  = var.rice_gcp_region
  user_project_override   = true
}
"""#
	"providers/gcp/variables.tf": #"""
# KING TODO map
# TODO:
# [ ] fill from infra/configs/opentofu.cue — no hardcoded IDs; use var.rice_* only
"""#
}
