name: Build

on:
    push:
        branches: [main, dev]
    pull_request:

jobs:
    bazel-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Bazel
              uses: bazelbuild/setup-bazel@v6
              with:
                  bazel-version: 7.2.1

            - name: Build with Bazel
              run: bazel build //...
