plugins {
    id 'java'
    id 'org.jetbrains.kotlin.jvm' version '1.9.0'
}

group = 'com.coderice'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.0'
    testImplementation 'junit:junit:4.13.2'
}

compileKotlin {
    kotlinOptions.jvmTarget = '17'
}



